import { useEffect, useRef } from "react";
import { Icon } from "@iconify/react";
import { Button } from "../Button";
import { Loader } from "../Loader";
import { useWorkspace } from "../../stores/workspace";
import { useDevelopSettings } from "../../stores/developSettings";
import { useNotifications } from "../../stores/notifications";
import { usePackageSessions } from "../../stores/packageSessions";
import {
  useDevelopSessions,
  initialPackagesSession,
  patchSession,
  getSession,
  registerSessionController,
  unregisterSessionController,
  type PackagesSession,
} from "../../stores/developSessions";
import type { TerminalSession } from "../PackageTerminalPane";
import type { PackageScript } from "./types";
import { parseNeuron } from "./types";
import { PackageRunStatusList } from "./shared/PackageRunStatusList";
import * as PackageService from "../../../../bindings/alis-hub-v3/packageservice";

interface PackagesPaneProps {
  tabId: string;
  neuron: string;
  neuronNames: string[];
}

export const PACKAGE_ACTIONS = [
  {
    value: "upgrade_defined",
    label: "Upgrade Defined",
    desc: "Upgrade packages generated by Define",
  },
  { value: "upgrade", label: "Upgrade All", desc: "Upgrade all specified packages" },
  { value: "install", label: "Install", desc: "Install all relevant packages" },
  { value: "add", label: "Add", desc: "Add packages from your Define steps" },
] as const;

export function PackagesPane({ tabId, neuron, neuronNames }: PackagesPaneProps) {
  const { state } = useWorkspace();
  const { addNotification } = useNotifications();
  const { settings: devSettings } = useDevelopSettings();
  const { sessions: packageSessions, addSessions, setTaskId } = usePackageSessions();

  const session = useDevelopSessions((s) => s.sessions[tabId]) as PackagesSession | undefined;
  const patch = (p: Partial<PackagesSession>) => patchSession<PackagesSession>(tabId, p);

  const orgRef = useRef(state.organisation);
  const productRef = useRef(state.product);
  orgRef.current = state.organisation;
  productRef.current = state.product;

  // Scan on mount
  useEffect(() => {
    useDevelopSessions.getState().ensureSession(initialPackagesSession(tabId, neuron, neuronNames));
    if (getSession<PackagesSession>(tabId)?.step === "scan") scan();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Imperative controller so other surfaces (command palette) can drive this flow.
  useEffect(() => {
    registerSessionController(tabId, {
      kind: "packages",
      scan: () => scanRef.current(),
      runPackages: () => runPackagesRef.current(),
      runScripts: (withVenv: boolean) => runScriptsRef.current(withVenv),
    });
    return () => unregisterSessionController(tabId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tabId]);

  async function scan() {
    patchSession<PackagesSession>(tabId, {
      step: "scan",
      scripts: [],
      selectedScripts: [],
      error: "",
    });
    try {
      const allScripts: PackageScript[] = [];
      for (const name of neuronNames) {
        const parsed = parseNeuron(name);
        const result = await PackageService.PreparePackageScripts(
          orgRef.current,
          productRef.current,
          parsed.id,
          parsed.version,
          devSettings.ignoreHiddenFolders,
          devSettings.ignoredFolderPatterns,
        );
        allScripts.push(...(result as PackageScript[]));
      }
      patchSession<PackagesSession>(tabId, {
        scripts: allScripts,
        selectedScripts: allScripts.map((s) => s.workDir),
        step: "select-action",
      });
    } catch (e: unknown) {
      patchSession<PackagesSession>(tabId, {
        error: e instanceof Error ? e.message : String(e),
        step: "select-action",
      });
    }
  }
  const scanRef = useRef(scan);
  scanRef.current = scan;

  async function doRunScripts(withVenv: boolean) {
    const current = getSession<PackagesSession>(tabId);
    if (!current) return;
    const toRun = current.scripts.filter((s) => current.selectedScripts.includes(s.workDir));
    if (toRun.length === 0 && !withVenv) return;
    patchSession<PackagesSession>(tabId, { step: "preparing" });
    const newSessions: TerminalSession[] = [];

    if (withVenv) {
      const venvRunID = `pkg-venv-${Date.now()}`;
      try {
        await PackageService.StartVenvSetup(venvRunID, orgRef.current, productRef.current);
        newSessions.push({ runID: venvRunID, title: ".venv setup", lang: "python", done: false });
      } catch {}
    }

    for (const script of toRun) {
      const cmd =
        current.action === "upgrade_defined"
          ? script.upgradeDefined
          : current.action === "upgrade"
            ? script.upgrade
            : current.action === "install"
              ? script.install
              : script.add;
      if (!cmd) continue;
      const runID = `pkg-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
      const title = script.name || script.workDir.split("/").slice(-2).join("/");
      try {
        await PackageService.StartPackageScript(runID, cmd, script.workDir);
        newSessions.push({ runID, title, lang: script.lang, done: false });
      } catch {}
    }

    if (newSessions.length > 0) {
      addSessions(newSessions);
      patchSession<PackagesSession>(tabId, { step: "running" });
      const neuronLabel =
        neuronNames.length === 1 ? neuronNames[0] : `${neuronNames.length} neurons`;
      const taskId = addNotification({
        severity: "info",
        source: "packages",
        title: "Packages running",
        body: neuronLabel,
        persistent: true,
        task: {
          type: "packages",
          status: "running",
          neuronId: neuronLabel,
          step: "running",
          startedAt: Date.now(),
          logBuffer: [],
          meta: { sessionIds: newSessions.map((s) => s.runID) },
        },
      });
      setTaskId(taskId);
    } else {
      patchSession<PackagesSession>(tabId, {
        error: "Failed to start any package scripts",
        step: "select-folders",
      });
    }
  }
  const runScriptsRef = useRef(doRunScripts);
  runScriptsRef.current = doRunScripts;

  async function handleRunPackages() {
    const current = getSession<PackagesSession>(tabId);
    if (!current) return;
    const toRun = current.scripts.filter((s) => current.selectedScripts.includes(s.workDir));
    if (toRun.length === 0) return;
    const hasPython = toRun.some((s) => s.lang === "python");
    if (hasPython) {
      const venvExists = await PackageService.CheckVenvExists(orgRef.current, productRef.current);
      if (!venvExists) {
        patchSession<PackagesSession>(tabId, { step: "venv-setup" });
        return;
      }
    }
    await doRunScripts(false);
  }
  const runPackagesRef = useRef(handleRunPackages);
  runPackagesRef.current = handleRunPackages;

  if (!session) return null;

  return (
    <>
      {session.step === "scan" && (
        <div className="flex-1 flex items-center justify-center">
          <div className="flex flex-col items-center gap-[12px]">
            <Loader size={20} />
            <p className="text-[11px] text-foreground/40">Scanning packages...</p>
          </div>
        </div>
      )}

      {session.step === "select-action" && (
        <div className="flex-1 overflow-y-auto px-[16px] py-[16px]">
          {session.error && (
            <div className="flex items-start gap-[8px] p-[10px] bg-[rgba(255,92,95,0.1)] border border-[rgba(255,92,95,0.3)] rounded-[6px] mb-[16px]">
              <Icon
                icon="solar:danger-triangle-linear"
                className="text-destructive text-sm shrink-0 mt-[1px]"
              />
              <p className="text-[10px] text-foreground/70 leading-relaxed">{session.error}</p>
            </div>
          )}
          <p className="text-[9px] text-foreground/40 uppercase font-bold font-mono mb-[10px]">
            Action
          </p>
          <div className="flex flex-col gap-[2px] mb-[20px]">
            {PACKAGE_ACTIONS.map(({ value, label, desc }) => (
              <button
                key={value}
                onClick={() => patch({ action: value })}
                className={`flex items-center gap-[10px] px-[12px] py-[10px] rounded-[6px] border transition-colors text-left ${
                  session.action === value
                    ? "bg-brand-fill/8 border-brand-fill/35 text-foreground"
                    : "bg-background border-border text-foreground/50 hover:border-border hover:text-foreground/70"
                }`}
              >
                <span
                  className={`size-[6px] rounded-full shrink-0 ${session.action === value ? "bg-brand-fill" : "bg-accent"}`}
                />
                <div className="flex-1 min-w-0">
                  <p className="text-[11px] font-medium">{label}</p>
                  <p className="text-[9px] text-foreground/35 leading-snug mt-[1px]">{desc}</p>
                </div>
              </button>
            ))}
          </div>
          <Button
            variant="primary"
            className="w-full justify-center py-[10px]"
            disabled={session.scripts.length === 0}
            onClick={() =>
              session.scripts.length === 1 ? handleRunPackages() : patch({ step: "select-folders" })
            }
          >
            {session.scripts.length === 1 ? "Run" : "Next →"}
          </Button>
          {session.scripts.length === 0 && !session.error && (
            <p className="text-[10px] text-foreground/30 text-center mt-[12px]">
              No package scripts available
            </p>
          )}
        </div>
      )}

      {session.step === "select-folders" && (
        <div className="flex-1 flex flex-col min-h-0">
          <div className="flex-1 overflow-y-auto">
            <div className="px-[16px] pt-[14px] pb-[8px]">
              <button
                onClick={() => patch({ step: "select-action" })}
                className="flex items-center gap-[6px] text-[10px] text-foreground/40 hover:text-foreground mb-[12px] transition-colors"
              >
                <Icon icon="solar:alt-arrow-left-linear" className="text-sm" />
                Back
              </button>
              <p className="text-[9px] text-foreground/40 uppercase font-bold font-mono">
                Select Folders
              </p>
            </div>
            <div className="flex flex-col">
              {session.scripts.map((s) => {
                const checked = session.selectedScripts.includes(s.workDir);
                return (
                  <button
                    key={s.workDir}
                    onClick={() =>
                      patch({
                        selectedScripts: checked
                          ? session.selectedScripts.filter((w) => w !== s.workDir)
                          : [...session.selectedScripts, s.workDir],
                      })
                    }
                    className={`text-left px-[16px] py-[10px] border-b border-border flex items-center gap-[10px] transition-colors ${checked ? "bg-brand-fill/4" : "hover:bg-foreground/[2%]"}`}
                  >
                    <span
                      className={`size-[14px] rounded-[3px] border flex items-center justify-center shrink-0 transition-colors ${checked ? "bg-brand-fill border-brand-fill" : "border-border"}`}
                    >
                      {checked && (
                        <Icon
                          icon="solar:check-linear"
                          className="text-brand-foreground text-[9px]"
                        />
                      )}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className="text-[11px] font-medium text-foreground truncate">
                        {s.name || s.workDir.split("/").slice(-2).join("/")}
                      </p>
                      <p className="text-[9px] text-foreground/35 font-mono uppercase leading-snug mt-[1px]">
                        {s.lang}
                      </p>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
          <div className="shrink-0 px-[14px] py-[10px] border-t border-border">
            <Button
              variant="primary"
              className="w-full justify-center py-[10px]"
              disabled={session.selectedScripts.length === 0}
              onClick={handleRunPackages}
            >
              Run · {session.selectedScripts.length} folder
              {session.selectedScripts.length !== 1 ? "s" : ""}
            </Button>
          </div>
        </div>
      )}

      {session.step === "venv-setup" && (
        <div className="flex-1 flex flex-col min-h-0 overflow-y-auto px-[16px] py-[16px]">
          <div className="flex items-start gap-[10px] p-[12px] bg-brand-fill/8 border border-brand-fill/25 rounded-[6px] mb-[20px]">
            <Icon
              icon="solar:info-circle-linear"
              className="text-brand text-base shrink-0 mt-[1px]"
            />
            <div>
              <p className="text-[11px] font-medium text-foreground leading-snug">
                Python virtual environment not found
              </p>
              <p className="text-[10px] text-foreground/50 leading-relaxed mt-[4px]">
                A <code className="font-mono text-brand">.venv</code> is required before running
                Python package scripts.
              </p>
            </div>
          </div>
          <div className="flex flex-col gap-[8px]">
            <Button
              variant="primary"
              className="w-full justify-center py-[10px]"
              onClick={() => doRunScripts(true)}
            >
              Create .venv &amp; Run
            </Button>
            <button
              onClick={() => doRunScripts(false)}
              className="w-full py-[9px] text-[10px] text-foreground/40 hover:text-foreground transition-colors font-mono uppercase"
            >
              Skip &amp; Run Anyway
            </button>
            <button
              onClick={() => patch({ step: "select-folders" })}
              className="w-full py-[9px] text-[10px] text-foreground/30 hover:text-foreground transition-colors font-mono"
            >
              ← Back
            </button>
          </div>
        </div>
      )}

      {session.step === "preparing" && (
        <div className="flex-1 flex items-center justify-center">
          <div className="flex flex-col items-center gap-[12px]">
            <Loader size={20} />
            <p className="text-[11px] text-foreground/40">Starting scripts...</p>
          </div>
        </div>
      )}

      {session.step === "running" && (
        <PackageRunStatusList
          sessions={packageSessions}
          footerText="Output in the terminal pane ↓"
        />
      )}
    </>
  );
}
