// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppInfo(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1048471896).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ApplyUpdate swaps the running bundle/binary with the staged one and
 * relaunches. macOS only for now; other platforms return an error.
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(440972242);
}

export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(2846454243).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(453372526);
}

/**
 * DownloadUpdate pulls the appropriate artifact for this platform, extracts
 * it to a temp directory, and stashes the resulting .app path. Progress is
 * reported over the "update:progress" event every ~100ms.
 * 
 * Returns the path to the extracted .app (macOS) or the binary (Linux).
 * Windows is not yet supported end-to-end — falls back to the release URL.
 */
export function DownloadUpdate(): $CancellablePromise<string> {
    return $Call.ByID(4121325632);
}

/**
 * OpenReleasePage asks the OS to open the latest-release URL in the default
 * browser. Used as a fallback when auto-download isn't supported.
 */
export function OpenReleasePage(): $CancellablePromise<void> {
    return $Call.ByID(3307677625);
}

/**
 * SetApp wires the Wails app so the service can emit runtime events.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3158555550, app);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.UpdateInfo.createFrom;
