// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GlassArtifact is one artifact type from ExplainDefine.
 */
export class GlassArtifact {
    "type": string;
    "state": number;
    "notes": string;
    "locationUri": string;

    /**
     * packageImportPath (Go) or packageName (JS)
     */
    "extra": string;

    /** Creates a new GlassArtifact instance. */
    constructor($$source: Partial<GlassArtifact> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("locationUri" in $$source)) {
            this["locationUri"] = "";
        }
        if (!("extra" in $$source)) {
            this["extra"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassArtifact instance from a string or object.
     */
    static createFrom($$source: any = {}): GlassArtifact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlassArtifact($$parsedSource as Partial<GlassArtifact>);
    }
}

/**
 * GlassDefinition holds current definition metadata from ExplainDefine.
 */
export class GlassDefinition {
    "name": string;
    "version": string;
    "commit": string;
    "releaseType": string;

    /** Creates a new GlassDefinition instance. */
    constructor($$source: Partial<GlassDefinition> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("releaseType" in $$source)) {
            this["releaseType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): GlassDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlassDefinition($$parsedSource as Partial<GlassDefinition>);
    }
}

/**
 * GlassResult is the response from ExplainDefine.
 */
export class GlassResult {
    "title": string;
    "summary": string;
    "definition": GlassDefinition;
    "artifacts": GlassArtifact[];

    /** Creates a new GlassResult instance. */
    constructor($$source: Partial<GlassResult> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = (new GlassDefinition());
        }
        if (!("artifacts" in $$source)) {
            this["artifacts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GlassResult {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definition" in $$parsedSource) {
            $$parsedSource["definition"] = $$createField2_0($$parsedSource["definition"]);
        }
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField3_0($$parsedSource["artifacts"]);
        }
        return new GlassResult($$parsedSource as Partial<GlassResult>);
    }
}

/**
 * PackageScript holds server-generated shell commands for one language folder.
 */
export class PackageScript {
    /**
     * display name: "asana-v1" or "asana-v1/proto"
     */
    "name": string;
    "title": string;
    "workDir": string;
    "lang": string;
    "install": string;
    "upgrade": string;
    "upgradeDefined": string;
    "add": string;

    /** Creates a new PackageScript instance. */
    constructor($$source: Partial<PackageScript> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("workDir" in $$source)) {
            this["workDir"] = "";
        }
        if (!("lang" in $$source)) {
            this["lang"] = "";
        }
        if (!("install" in $$source)) {
            this["install"] = "";
        }
        if (!("upgrade" in $$source)) {
            this["upgrade"] = "";
        }
        if (!("upgradeDefined" in $$source)) {
            this["upgradeDefined"] = "";
        }
        if (!("add" in $$source)) {
            this["add"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageScript instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageScript {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageScript($$parsedSource as Partial<PackageScript>);
    }
}

// Private type creation functions
const $$createType0 = GlassDefinition.createFrom;
const $$createType1 = GlassArtifact.createFrom;
const $$createType2 = $Create.Array($$createType1);
