import { LearningModule } from '../types';
import { GrpcFlowDiagram } from '../diagrams/GrpcFlowDiagram';

const protoExample = `syntax = "proto3";

package acme.payments.v1;

import "google/api/annotations.proto";

// A payment represents a transfer of funds.
message Payment {
  string name = 1;        // payments/{payment}
  string amount = 2;      // e.g. "100.00"
  string currency = 3;    // ISO 4217, e.g. "USD"
  string state = 4;       // PENDING | COMPLETED | FAILED
}

service PaymentsService {
  // CreatePayment initiates a new payment.
  rpc CreatePayment(CreatePaymentRequest) returns (Payment) {
    option (google.api.http) = {
      post: "/v1/payments"
      body: "payment"
    };
  }

  // GetPayment retrieves a payment by name.
  rpc GetPayment(GetPaymentRequest) returns (Payment) {
    option (google.api.http) = {
      get: "/v1/{name=payments/*}"
    };
  }
}

message CreatePaymentRequest {
  Payment payment = 1;
}

message GetPaymentRequest {
  string name = 1;
}`;

const generatedGoExample = `// Generated by protoc — do not edit.

// PaymentsServiceServer is the server interface.
// Your implementation must satisfy this interface.
type PaymentsServiceServer interface {
  CreatePayment(context.Context, *CreatePaymentRequest) (*Payment, error)
  GetPayment(context.Context, *GetPaymentRequest) (*Payment, error)
}

// PaymentsServiceClient is the client stub.
// Use this to call the service from any Go program.
type PaymentsServiceClient interface {
  CreatePayment(ctx context.Context, in *CreatePaymentRequest, ...) (*Payment, error)
  GetPayment(ctx context.Context, in *GetPaymentRequest, ...) (*Payment, error)
}`;

export const module2: LearningModule = {
  id: 'module2',
  title: 'Define',
  subtitle: 'Protocol Buffers and service contracts',
  icon: 'solar:document-text-linear',
  steps: [
    {
      id: 'm2-s0',
      title: 'Why Protocol Buffers instead of REST?',
      body: (
        <div className="flex flex-col gap-[12px]">
          <p className="text-[12px] text-[rgba(255,255,255,0.7)] leading-[1.7]">
            Traditional REST APIs are informal — the "contract" is usually a README or a Swagger doc that someone
            wrote once and never updated. Every team invents its own conventions for naming, pagination, error codes,
            and authentication.
          </p>
          <p className="text-[12px] text-[rgba(255,255,255,0.7)] leading-[1.7]">
            <span className="text-white font-bold">Protocol Buffers</span> (protobuf) are a{' '}
            <span className="text-white">machine-readable</span> contract. You describe your service — its methods, request
            types, and response types — in a <code className="text-brand text-[11px]">.proto</code> file.
            That file becomes the source of truth for every consumer and every implementation.
          </p>
          <div className="flex flex-col gap-[8px]">
            {[
              { label: 'Strongly typed', desc: 'Every field has an explicit type. No more guessing if "amount" is a string or a number.' },
              { label: 'Code generated', desc: 'Client stubs and server interfaces are generated automatically — no hand-written HTTP clients.' },
              { label: 'Versioned', desc: 'Service versions (v1, v2) are explicit in the package name. Breaking changes are intentional.' },
              { label: 'Language agnostic', desc: 'The same .proto generates Go, TypeScript, Python, Java, and more from one definition.' },
            ].map(({ label, desc }) => (
              <div key={label} className="flex items-start gap-[10px] px-[12px] py-[8px] bg-muted border border-border rounded-[4px]">
                <div className="size-[6px] rounded-full bg-brand mt-[5px] shrink-0" />
                <div>
                  <span className="text-[11px] font-bold text-white font-mono">{label} </span>
                  <span className="text-[11px] text-[rgba(255,255,255,0.5)]">— {desc}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      ),
    },
    {
      id: 'm2-s1',
      title: 'Writing a .proto file',
      body: (
        <div className="flex flex-col gap-[12px]">
          <p className="text-[12px] text-[rgba(255,255,255,0.7)] leading-[1.7]">
            A proto file has three parts: the <strong className="text-white">messages</strong> (your data structures),
            the <strong className="text-white">service</strong> (your API methods), and{' '}
            <strong className="text-white">HTTP bindings</strong> (REST mappings via Google's api annotations).
          </p>
          <p className="text-[12px] text-[rgba(255,255,255,0.7)] leading-[1.7]">
            alis follows{' '}
            <span className="text-white">Google's API Design Guide</span> — resources have
            a <code className="text-brand text-[11px]">name</code> field, methods use standard verbs
            (Create, Get, List, Update, Delete), and HTTP bindings follow REST resource patterns.
          </p>
          <p className="text-[11px] text-[rgba(255,255,255,0.4)] leading-[1.5]">
            Here's a real example — a PaymentsService with two methods:
          </p>
          <div className="bg-background border border-border rounded-[4px] overflow-hidden">
            <div className="px-[12px] py-[6px] border-b border-border bg-card">
              <p className="text-[9px] text-[rgba(255,255,255,0.5)] uppercase font-bold font-mono">
                payments.proto
              </p>
            </div>
            <pre className="p-[12px] overflow-x-auto">
              <code className="text-[10px] leading-[1.6] text-[rgba(255,255,255,0.85)] font-mono whitespace-pre">
                {protoExample}
              </code>
            </pre>
          </div>
        </div>
      ),
      diagram: <GrpcFlowDiagram />,
    },
    {
      id: 'm2-s2',
      title: 'What alis generate produces',
      body: (
        <div className="flex flex-col gap-[12px]">
          <p className="text-[12px] text-[rgba(255,255,255,0.7)] leading-[1.7]">
            Running <code className="text-brand text-[11px]">alis generate</code> (or triggering it
            via the VS Code extension) compiles your <code className="text-[11px] text-[rgba(255,255,255,0.6)]">.proto</code> files
            through <code className="text-[11px] text-[rgba(255,255,255,0.6)]">protoc</code> and produces:
          </p>
          <div className="flex flex-col gap-[6px]">
            {[
              { file: 'pb.go', desc: 'Go structs for all message types, with JSON/proto marshalling.' },
              { file: 'grpc.pb.go', desc: 'The server interface your Go code must implement, plus the client stub.' },
              { file: 'pb.gw.go', desc: 'HTTP→gRPC transcoding gateway (serves REST calls alongside gRPC).' },
              { file: 'openapi.json', desc: 'OpenAPI v3 spec, auto-generated from the proto HTTP bindings.' },
            ].map(({ file, desc }) => (
              <div key={file} className="flex items-start gap-[10px] px-[10px] py-[8px] bg-background border border-border rounded-[4px]">
                <code className="text-[10px] font-mono text-brand shrink-0 w-[140px]">*_{file}</code>
                <p className="text-[11px] text-[rgba(255,255,255,0.5)]">{desc}</p>
              </div>
            ))}
          </div>
          <div className="bg-background border border-border rounded-[4px] overflow-hidden">
            <div className="px-[12px] py-[6px] border-b border-border bg-card">
              <p className="text-[9px] text-[rgba(255,255,255,0.5)] uppercase font-bold font-mono">
                payments_grpc.pb.go (generated)
              </p>
            </div>
            <pre className="p-[12px] overflow-x-auto">
              <code className="text-[10px] leading-[1.6] text-[rgba(255,255,255,0.85)] font-mono whitespace-pre">
                {generatedGoExample}
              </code>
            </pre>
          </div>
          <p className="text-[11px] text-[rgba(255,255,255,0.4)] leading-[1.5]">
            You never edit these generated files directly. They are regenerated every time the proto changes.
            Your implementation code lives in separate files that{' '}
            <em>import</em> the generated interfaces.
          </p>
        </div>
      ),
    },
    {
      id: 'm2-s3',
      title: 'Implementing the server interface',
      body: (
        <div className="flex flex-col gap-[12px]">
          <p className="text-[12px] text-[rgba(255,255,255,0.7)] leading-[1.7]">
            Once generated, your job is to implement the server interface in Go. The interface is strict —
            if your proto adds a new method, the compiler will refuse to build until your implementation handles it.
            This is the key advantage over REST: the contract enforces completeness at compile time.
          </p>
          <p className="text-[11px] text-[rgba(255,255,255,0.4)] leading-[1.5]">
            A typical implementation file looks like this:
          </p>
          <div className="px-[12px] py-[10px] bg-background border border-border rounded-[4px]">
            <pre className="text-[10px] font-mono text-[rgba(255,255,255,0.75)] leading-[1.6] whitespace-pre overflow-x-auto">
{`type server struct {
  db *sql.DB
}

// CreatePayment implements PaymentsServiceServer.
func (s *server) CreatePayment(
  ctx context.Context,
  req *pb.CreatePaymentRequest,
) (*pb.Payment, error) {
  // Your business logic here
  return &pb.Payment{Name: "payments/123"}, nil
}`}
            </pre>
          </div>
          <div className="flex items-start gap-[10px] px-[14px] py-[12px] bg-[rgba(248,129,169,0.06)] border border-[rgba(248,129,169,0.2)] rounded-[4px]">
            <p className="text-[11px] text-[rgba(255,255,255,0.6)] leading-[1.5]">
              <span className="text-brand font-bold">Key insight: </span>
              the generated interface is the only coupling between your business logic and the transport layer.
              Your code never touches HTTP verbs, JSON parsing, or header handling — gRPC handles all of that.
            </p>
          </div>
        </div>
      ),
    },
  ],
};
