// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuildService is a Wails-bound service that orchestrates the Build flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FetchBuildLogs fetches the current log page from the alisproxy, extracts plain text,
 * and returns only the characters past textOffset. Pass 0 on the first call;
 * pass the returned NextOffset on each subsequent call to stream only new lines.
 */
export function FetchBuildLogs(logsUrl: string, textOffset: number): $CancellablePromise<$models.BuildLogsResult | null> {
    return $Call.ByID(4138132714, logsUrl, textOffset).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetBuildBranches lists remote branches in the build repository for a given product.
 */
export function GetBuildBranches(org: string, product: string): $CancellablePromise<string[]> {
    return $Call.ByID(2296824361, org, product).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetBuildCommits lists recent commits from the build repository.
 * branch is the remote branch name (without "origin/" prefix); defaults to "master" if empty.
 */
export function GetBuildCommits(org: string, product: string, neuron: string, version: string, branch: string, count: number): $CancellablePromise<$models.DefineCommit[]> {
    return $Call.ByID(3945634653, org, product, neuron, version, branch, count).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetCurrentBranch returns the currently checked-out branch name in the product build directory.
 */
export function GetCurrentBranch(org: string, product: string): $CancellablePromise<string> {
    return $Call.ByID(215098928, org, product);
}

/**
 * GetNeuronLastCommitTimes returns a map of neuron ID (e.g. "bff-v1") → ISO-8601 timestamp of
 * the last commit that touched that neuron's directory on the given branch. Neuron directories
 * on disk are laid out as <base>/<version>/ (e.g. bookings/v1, bookings/v2); this walks each
 * base folder's version subdirectories and keys results as "<base>-<version>" to match the
 * neuron ID convention used elsewhere (e.g. product overview, scanDockerfiles). Neurons with no
 * matching commits are omitted from the result.
 */
export function GetNeuronLastCommitTimes(org: string, product: string, branch: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2006141021, org, product, branch).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * PollBuildOperation checks the status of a running Build operation.
 * neuron is the full neuron resource name (needed to construct the logs URL when the API doesn't return one).
 */
export function PollBuildOperation(name: string, neuron: string): $CancellablePromise<$models.RunBuildResult | null> {
    return $Call.ByID(2685900073, name, neuron).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * PollLocalBuild returns new output from a running local Docker build.
 * Pass 0 as offset on first call; pass NextOffset from each response on subsequent calls.
 */
export function PollLocalBuild(buildID: string, offset: number): $CancellablePromise<$models.LocalBuildChunk | null> {
    return $Call.ByID(4081576225, buildID, offset).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * RunBuild starts a Build operation on the Alis backend.
 */
export function RunBuild(neuron: string, commit: string): $CancellablePromise<$models.RunBuildResult | null> {
    return $Call.ByID(1354516010, neuron, commit).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SetBackend(b: $models.DBDBackend): $CancellablePromise<void> {
    return $Call.ByID(1370141225, b);
}

/**
 * StartLocalBuild launches a local Docker build in a goroutine and returns
 * a build ID that can be passed to PollLocalBuild to stream output.
 * neuron is the full resource name e.g. "organisations/voyage/products/vp/neurons/hubspot-v1".
 */
export function StartLocalBuild(neuron: string, commit: string): $CancellablePromise<$models.LocalBuildResult | null> {
    return $Call.ByID(1986611470, neuron, commit).then(($result: any) => {
        return $$createType11($result);
    });
}

// Private type creation functions
const $$createType0 = $models.BuildLogsResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.DefineCommit.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $models.RunBuildResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.LocalBuildChunk.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.LocalBuildResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
