// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuildService is a Wails-bound service that orchestrates the Build flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetBuildCommits lists recent commits from the build repository.
 * @param {string} org
 * @param {string} product
 * @param {string} neuron
 * @param {string} version
 * @param {number} count
 * @returns {$CancellablePromise<$models.DefineCommit[]>}
 */
export function GetBuildCommits(org, product, neuron, version, count) {
    return $Call.ByID(3945634653, org, product, neuron, version, count).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PollBuildOperation checks the status of a running Build operation.
 * neuron is the full neuron resource name (needed to construct the logs URL when the API doesn't return one).
 * @param {string} name
 * @param {string} neuron
 * @returns {$CancellablePromise<$models.RunBuildResult | null>}
 */
export function PollBuildOperation(name, neuron) {
    return $Call.ByID(2685900073, name, neuron).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RunBuild starts a Build operation on the Alis backend.
 * @param {string} neuron
 * @param {string} commit
 * @returns {$CancellablePromise<$models.RunBuildResult | null>}
 */
export function RunBuild(neuron, commit) {
    return $Call.ByID(1354516010, neuron, commit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DefineCommit.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RunBuildResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
