// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuildService is a Wails-bound service that orchestrates the Build flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetBuildCommits lists recent commits from the build repository.
 */
export function GetBuildCommits(org: string, product: string, neuron: string, version: string, count: number): $CancellablePromise<$models.DefineCommit[]> {
    return $Call.ByID(3945634653, org, product, neuron, version, count).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PollBuildOperation checks the status of a running Build operation.
 * neuron is the full neuron resource name (needed to construct the logs URL when the API doesn't return one).
 */
export function PollBuildOperation(name: string, neuron: string): $CancellablePromise<$models.RunBuildResult | null> {
    return $Call.ByID(2685900073, name, neuron).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RunBuild starts a Build operation on the Alis backend.
 */
export function RunBuild(neuron: string, commit: string): $CancellablePromise<$models.RunBuildResult | null> {
    return $Call.ByID(1354516010, neuron, commit).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DefineCommit.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RunBuildResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
