// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuildService is a Wails-bound service that orchestrates the Build flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FetchBuildLogs fetches the current log page from the alisproxy, extracts plain text,
 * and returns only the characters past textOffset. Pass 0 on the first call;
 * pass the returned NextOffset on each subsequent call to stream only new lines.
 */
export function FetchBuildLogs(logsUrl: string, textOffset: number): $CancellablePromise<$models.BuildLogsResult | null> {
    return $Call.ByID(4138132714, logsUrl, textOffset).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetBuildCommits lists recent commits from the build repository.
 */
export function GetBuildCommits(org: string, product: string, neuron: string, version: string, count: number): $CancellablePromise<$models.DefineCommit[]> {
    return $Call.ByID(3945634653, org, product, neuron, version, count).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PollBuildOperation checks the status of a running Build operation.
 * neuron is the full neuron resource name (needed to construct the logs URL when the API doesn't return one).
 */
export function PollBuildOperation(name: string, neuron: string): $CancellablePromise<$models.RunBuildResult | null> {
    return $Call.ByID(2685900073, name, neuron).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RunBuild starts a Build operation on the Alis backend.
 */
export function RunBuild(neuron: string, commit: string): $CancellablePromise<$models.RunBuildResult | null> {
    return $Call.ByID(1354516010, neuron, commit).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.BuildLogsResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DefineCommit.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.RunBuildResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
