// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BuildKitService is a Wails-bound service for Build Kit operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListBuildSpecs returns all build specs accessible to the current user.
 * Status values: 0=UNSPECIFIED, 1=NEW, 2=ACTIVE, 3=COMPLETED
 */
export function ListBuildSpecs(): $CancellablePromise<$models.BuildSpecItem[]> {
    return $Call.ByID(68303133).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.BuildSpecItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
