// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetReleaseNotes returns the markdown body for the current version from CHANGELOG.md.
 * Returns an empty string if no matching section is found.
 * @returns {$CancellablePromise<string>}
 */
export function GetReleaseNotes() {
    return $Call.ByID(2218651651);
}
