// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CLIService provides CLI-backed operations for packages, code blocks, and
 * environment management. It is a Wails-bound service that can be called
 * from the frontend as an alternative to the gRPC/Console API paths.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CLIBlocksInstall runs `alis blocks install <blockId> [<pkg>] --json`.
 */
export function CLIBlocksInstall(blockID: string, pkg: string): $CancellablePromise<string> {
    return $Call.ByID(3916844836, blockID, pkg);
}

/**
 * CLIBlocksList runs `alis blocks list [<pkg>] --json`.
 */
export function CLIBlocksList(pkg: string): $CancellablePromise<string> {
    return $Call.ByID(2198367741, pkg);
}

/**
 * CLIBlocksMerge runs `alis blocks merge <blockId> [<pkg>] --json`.
 */
export function CLIBlocksMerge(blockID: string, pkg: string): $CancellablePromise<string> {
    return $Call.ByID(513037835, blockID, pkg);
}

/**
 * CLIBlocksUninstall runs `alis blocks uninstall <blockId> [<pkg>] --json`.
 */
export function CLIBlocksUninstall(blockID: string, pkg: string): $CancellablePromise<string> {
    return $Call.ByID(254453117, blockID, pkg);
}

/**
 * CLIBlocksUpgrade runs `alis blocks upgrade <blockId> [<pkg>] --json`.
 */
export function CLIBlocksUpgrade(blockID: string, pkg: string): $CancellablePromise<string> {
    return $Call.ByID(2916780011, blockID, pkg);
}

/**
 * CLIBlocksVersions runs `alis blocks versions <blockId> --json`.
 */
export function CLIBlocksVersions(blockID: string): $CancellablePromise<string> {
    return $Call.ByID(1526017240, blockID);
}

/**
 * CLIContextView runs `alis context view [<ref>] --json`.
 */
export function CLIContextView(ref: string): $CancellablePromise<string> {
    return $Call.ByID(720275183, ref);
}

/**
 * CLIEnvBranches runs `alis environment branches [<org>.<product>.<env>] --json`.
 */
export function CLIEnvBranches(ref: string): $CancellablePromise<string> {
    return $Call.ByID(919447698, ref);
}

/**
 * CLIEnvRefresh runs `alis environment refresh <org>.<product>.<env> --json`.
 */
export function CLIEnvRefresh(org: string, product: string, env: string): $CancellablePromise<string> {
    return $Call.ByID(4076239137, org, product, env);
}

/**
 * CLIEnvSet runs `alis environment set <org>.<product>.<env> KEY=VALUE --json`.
 */
export function CLIEnvSet(org: string, product: string, env: string, key: string, value: string): $CancellablePromise<string> {
    return $Call.ByID(831421706, org, product, env, key, value);
}

/**
 * CLIEnvUnset runs `alis environment unset <org>.<product>.<env> KEY --json`.
 */
export function CLIEnvUnset(org: string, product: string, env: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(3428595951, org, product, env, key);
}

/**
 * CLIEnvVariables runs `alis environment variables <org>.<product> --json`.
 */
export function CLIEnvVariables(org: string, product: string): $CancellablePromise<string> {
    return $Call.ByID(2865833575, org, product);
}

/**
 * CLIPackagesInstall runs `alis packages install <pkg> --json`.
 */
export function CLIPackagesInstall(pkg: string): $CancellablePromise<string> {
    return $Call.ByID(1524925609, pkg);
}

/**
 * CLIPackagesUpgrade runs `alis packages upgrade <pkg> --json [--all]`.
 */
export function CLIPackagesUpgrade(pkg: string, all: boolean): $CancellablePromise<string> {
    return $Call.ByID(3648102162, pkg, all);
}
