// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CLIService is the Wails-bound surface for alis CLI capabilities that have
 * no counterpart elsewhere in the app: skills, ask, diagnostics, accounts,
 * resource creation and operation inspection (see cliservice_skills.go and
 * cliservice_platform.go), plus package management and context resolution.
 * 
 * Code blocks and environments deliberately live on ProductService instead,
 * next to their Console API counterparts and with decoded result types —
 * two doors to the same command is how the two paths drift apart.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Ask answers a question from the caller's coding sessions, support
 * conversations and shared skills. Access is enforced at retrieval, so it can
 * only ever draw on what this user can already see.
 * 
 * session continues an earlier conversation; pass the Session from a previous
 * answer. Exit 1 with `no_answer` means rephrase rather than retry.
 */
export function Ask(question: string, session: string): $CancellablePromise<$models.AskAnswer | null> {
    return $Call.ByID(825038012, question, session).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CLIContextView runs `alis context view [<ref>] --json`.
 * 
 * Which fields come back depends on the working directory: packageId and
 * serviceFolder appear only when dir is inside a service folder, and the
 * environments array only when it is not. Pass dir explicitly — the app's own
 * cwd is "/" under a Finder launch, where nothing resolves.
 */
export function CLIContextView(ref: string, dir: string): $CancellablePromise<string> {
    return $Call.ByID(720275183, ref, dir);
}

/**
 * CLIPackagesInstall runs `alis packages install <pkg> --json`.
 * language, when set, limits the run to one of go/node/python/dart.
 */
export function CLIPackagesInstall(pkg: string, language: string, version: string): $CancellablePromise<string> {
    return $Call.ByID(1524925609, pkg, language, version);
}

/**
 * CLIPackagesUpgrade runs `alis packages upgrade <pkg> --json`.
 * 
 * all upgrades third-party packages too, not just alis.build ones. paths
 * selects specific package folders or manifests relative to the service, which
 * is how nested modules are addressed.
 */
export function CLIPackagesUpgrade(pkg: string, all: boolean, language: string, paths: string[]): $CancellablePromise<string> {
    return $Call.ByID(3648102162, pkg, all, language, paths);
}

/**
 * CLIVersion returns the installed alis CLI version, or an empty string when
 * the CLI is not available.
 */
export function CLIVersion(): $CancellablePromise<string> {
    return $Call.ByID(1057680553);
}

/**
 * DescribeOperation polls an operation without blocking. Use it to re-check an
 * operation the app started earlier, for instance after a restart.
 */
export function DescribeOperation(name: string): $CancellablePromise<$models.OperationSnapshot | null> {
    return $Call.ByID(335300835, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Doctor collects a local diagnostics snapshot.
 * 
 * Nothing is uploaded: --ticket is deliberately not exposed here, so this stays
 * a read-only local call. The log tail is excluded too, since it can contain
 * paths and command lines the user has not chosen to share.
 */
export function Doctor(): $CancellablePromise<$models.Diagnostics | null> {
    return $Call.ByID(1343375984).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * FollowOperation re-attaches to an operation and streams its progress as
 * dbd:progress / dbd:done events, the same channel the DBD services use.
 * 
 * It returns immediately. Interrupting a wait never cancels the operation, so
 * this is safe to call repeatedly — following an operation already being
 * followed is a no-op.
 */
export function FollowOperation(name: string, kind: string): $CancellablePromise<void> {
    return $Call.ByID(683097643, name, kind);
}

/**
 * GcloudAuthHostsForProduct lists the configured registry hosts for a product.
 * 
 * `alis gcloud auth --json` also returns live access tokens; those are dropped
 * here rather than crossing the Wails boundary into a renderer where they could
 * end up in logs or devtools.
 */
export function GcloudAuthHostsForProduct(org: string, product: string): $CancellablePromise<$models.GcloudAuthHosts | null> {
    return $Call.ByID(3848105804, org, product).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GitRemotesForProduct returns the product's repo URLs and git identity.
 */
export function GitRemotesForProduct(org: string, product: string): $CancellablePromise<$models.GitRemotes | null> {
    return $Call.ByID(2444185114, org, product).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListAccounts returns the accounts eligible to own Build usage.
 * 
 * This is the one command that returns snake_case keys.
 */
export function ListAccounts(): $CancellablePromise<$models.BuildAccountInfo[]> {
    return $Call.ByID(2919905703).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * NewProduct creates a product via `alis product new <org>.<product>`.
 */
export function NewProduct(org: string, product: string, displayName: string): $CancellablePromise<string> {
    return $Call.ByID(1373071514, org, product, displayName);
}

/**
 * NewService creates a service via `alis service new <package-id>`.
 * 
 * packageID is the full <org>.<product>.<path>.<vN> form, which maps
 * deterministically to the neuron resource and the on-disk folders.
 */
export function NewService(packageID: string): $CancellablePromise<string> {
    return $Call.ByID(524433830, packageID);
}

/**
 * PushSession saves a local coding-agent session transcript to Alis history.
 * harness narrows the search to claude-code, codex or gemini.
 */
export function PushSession(session: string, harness: string): $CancellablePromise<string> {
    return $Call.ByID(2433770833, session, harness);
}

/**
 * ScanSessions scans local harness transcripts once and pushes telemetry events.
 */
export function ScanSessions(): $CancellablePromise<string> {
    return $Call.ByID(583208895);
}

/**
 * SelectAccount sets the active Build account.
 * 
 * Never call this on the user's behalf. When a command fails with
 * ACTIVE_BUILD_ACCOUNT_REQUIRED, list the accounts, ask which should own Build
 * subscriptions and billing, and only then select — it is a billing decision.
 */
export function SelectAccount(account: string): $CancellablePromise<string> {
    return $Call.ByID(2972588358, account);
}

/**
 * SkillsCreate scaffolds a new skill workspace under ~/.alis/skills/workspaces.
 * Skill ids are global, so this fails with `skill_exists` if taken.
 */
export function SkillsCreate(id: string, name: string, description: string): $CancellablePromise<string> {
    return $Call.ByID(1329779641, id, name, description);
}

/**
 * SkillsDelete soft-deletes a skill you administer; republishing restores it.
 * Deletion is destructive, so expect an exit-3 approval gate.
 */
export function SkillsDelete(id: string): $CancellablePromise<string> {
    return $Call.ByID(495782926, id);
}

/**
 * SkillsEdit downloads one of your published skills into a workspace.
 * refresh discards local edits and re-downloads. Only skills you authored are
 * editable; others fail with `not_editable`.
 */
export function SkillsEdit(id: string, refresh: boolean): $CancellablePromise<string> {
    return $Call.ByID(244902829, id, refresh);
}

/**
 * SkillsFeedback sends feedback to a skill's owner. rating is "up" or "down".
 */
export function SkillsFeedback(id: string, message: string, rating: string): $CancellablePromise<string> {
    return $Call.ByID(1415499334, id, message, rating);
}

/**
 * SkillsInstall installs a registry skill into a local agent harness.
 * 
 * project installs into the current repo's .claude/skills/<id> instead of the
 * user scope. force takes over a target folder that exists but was not written
 * by alis — which is why it is opt-in: without it the CLI reports
 * `unmanaged_target` rather than overwriting someone's hand-written skill.
 */
export function SkillsInstall(id: string, harness: string, project: boolean, force: boolean): $CancellablePromise<string> {
    return $Call.ByID(31847436, id, harness, project, force);
}

/**
 * SkillsInstalled lists skills installed into local agent harnesses.
 * 
 * This response is a bare JSON array, not an object with a wrapper key — unlike
 * every other skills command.
 */
export function SkillsInstalled(): $CancellablePromise<$models.InstalledSkill[]> {
    return $Call.ByID(3231522045).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SkillsList returns the whole catalog, for browsing rather than searching.
 */
export function SkillsList(): $CancellablePromise<$models.SkillDetail[]> {
    return $Call.ByID(10288693).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * SkillsLoad returns a skill's markdown instructions.
 * 
 * session attributes the load to a coding session; empty lets the CLI fall back
 * to $CLAUDE_SESSION_ID and then $ALIS_SESSION_ID.
 */
export function SkillsLoad(id: string, session: string): $CancellablePromise<string> {
    return $Call.ByID(1662123909, id, session);
}

/**
 * SkillsPublish validates and publishes a workspace.
 * 
 * If the registry changed since the workspace was downloaded the CLI exits 3
 * with `remote_changed`; force overwrites. clean removes the workspace after a
 * successful publish.
 */
export function SkillsPublish(id: string, name: string, force: boolean, clean: boolean): $CancellablePromise<string> {
    return $Call.ByID(3049942260, id, name, force, clean);
}

/**
 * SkillsRequest asks the Alis Build team for a skill that does not exist yet.
 */
export function SkillsRequest(name: string, description: string, useCase: string, notes: string): $CancellablePromise<string> {
    return $Call.ByID(2366047502, name, description, useCase, notes);
}

/**
 * SkillsResource fetches a file a skill's instructions reference. The path must
 * be written exactly as it appears in those instructions.
 */
export function SkillsResource(id: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(142013753, id, path);
}

/**
 * SkillsSearch ranks the catalog semantically for a natural-language query.
 */
export function SkillsSearch(query: string): $CancellablePromise<$models.SkillSummary[]> {
    return $Call.ByID(2286430197, query).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * SkillsShare grants or revokes access to one of your skills. email shares with
 * a colleague on your own domain; domain shares with everyone on it; remove
 * revokes the given access instead of granting it.
 */
export function SkillsShare(id: string, email: string, domain: boolean, remove: boolean): $CancellablePromise<string> {
    return $Call.ByID(3058756588, id, email, domain, remove);
}

/**
 * SkillsUninstall removes a locally installed skill. project limits removal to
 * project-scope installs.
 */
export function SkillsUninstall(id: string, harness: string, project: boolean): $CancellablePromise<string> {
    return $Call.ByID(3235572629, id, harness, project);
}

/**
 * SkillsUpgrade upgrades tracked installs. With no ids, all is required —
 * upgrading nothing silently would look like success.
 */
export function SkillsUpgrade(ids: string[], all: boolean): $CancellablePromise<string> {
    return $Call.ByID(1856380051, ids, all);
}

// Private type creation functions
const $$createType0 = $models.AskAnswer.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.OperationSnapshot.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.Diagnostics.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GcloudAuthHosts.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.GitRemotes.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.BuildAccountInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.InstalledSkill.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.SkillDetail.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.SkillSummary.createFrom;
const $$createType17 = $Create.Array($$createType16);
