// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DefineService is a Wails-bound service that orchestrates the Define flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDefineCommits lists recent commits from the define repository.
 */
export function GetDefineCommits(org: string, product: string, neuron: string, version: string, count: number): $CancellablePromise<$models.DefineCommit[]> {
    return $Call.ByID(387817029, org, product, neuron, version, count).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PollDefineOperation checks the status of a running Define operation.
 */
export function PollDefineOperation(name: string): $CancellablePromise<$models.RunDefineResult | null> {
    return $Call.ByID(3463411517, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RunDefine starts a Define operation on the Alis backend.
 */
export function RunDefine(neuron: string, commit: string, releaseType: string): $CancellablePromise<$models.RunDefineResult | null> {
    return $Call.ByID(1940816492, neuron, commit, releaseType).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ScanNeuronPackages(org: string, product: string, neuron: string, version: string): $CancellablePromise<$models.PackageInfo[]> {
    return $Call.ByID(3292503717, org, product, neuron, version).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DefineCommit.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RunDefineResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.PackageInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
