// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeployService is a Wails-bound service that orchestrates the Deploy flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FetchDeployLogs fetches log output from a deploy logs URL.
 * Pass 0 as textOffset on the first call; pass the returned NextOffset on subsequent calls.
 * @param {string} logsUrl
 * @param {number} textOffset
 * @returns {$CancellablePromise<$models.BuildLogsResult | null>}
 */
export function FetchDeployLogs(logsUrl, textOffset) {
    return $Call.ByID(2245220654, logsUrl, textOffset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListNeuronVersions returns built/retagged versions for a neuron, newest first.
 * neuron is the full neuron resource name e.g. "organisations/x/products/y/neurons/bff-v1".
 * @param {string} neuron
 * @returns {$CancellablePromise<($models.NeuronVersionSummary | null)[]>}
 */
export function ListNeuronVersions(neuron) {
    return $Call.ByID(2710712652, neuron).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * PollDeployOperation checks the status of a running Deploy operation.
 * @param {string} name
 * @returns {$CancellablePromise<$models.RunDeployResult | null>}
 */
export function PollDeployOperation(name) {
    return $Call.ByID(981273681, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * RunDeploy starts a Deploy operation on the Alis backend.
 * environments is a list of environment resource names (e.g. ["organisations/x/products/y/environments/dev"]).
 * neuron is the full neuron resource name. version is the neuron version to deploy.
 * planOnly runs terraform plan only; beta allows beta-state neurons to be deployed.
 * @param {string} neuron
 * @param {string} version
 * @param {string[]} environments
 * @param {boolean} planOnly
 * @param {boolean} beta
 * @returns {$CancellablePromise<$models.RunDeployResult | null>}
 */
export function RunDeploy(neuron, version, environments, planOnly, beta) {
    return $Call.ByID(333160816, neuron, version, environments, planOnly, beta).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.BuildLogsResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.NeuronVersionSummary.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.RunDeployResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
