// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GCloudService exposes GCP REST API tools to the frontend.
 * Auth is via `gcloud auth print-access-token` — cached for 45 minutes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckGCloudStatus reports whether gcloud is installed and can produce a valid
 * access token. It uses print-access-token (not just auth list) so it matches
 * exactly what the API calls require.
 * @returns {$CancellablePromise<$models.GCloudStatus>}
 */
export function CheckGCloudStatus() {
    return $Call.ByID(4101128005).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExecuteSpannerDML runs a DELETE or UPDATE statement using a partitioned DML
 * transaction, which does not require an explicit commit.
 * @param {string} databaseResourceName
 * @param {string} sql
 * @returns {$CancellablePromise<$models.SpannerDMLResult | null>}
 */
export function ExecuteSpannerDML(databaseResourceName, sql) {
    return $Call.ByID(1040902000, databaseResourceName, sql).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ExecuteSpannerQuery runs a read-only SQL query against a Spanner database.
 * databaseResourceName is the full name e.g. "projects/{p}/instances/{i}/databases/{d}".
 * Spanner's executeSql is session-scoped: we create a session, run the query, then delete it.
 * @param {string} databaseResourceName
 * @param {string} sql
 * @returns {$CancellablePromise<$models.SpannerQueryResult | null>}
 */
export function ExecuteSpannerQuery(databaseResourceName, sql) {
    return $Call.ByID(1045440973, databaseResourceName, sql).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetObjectContent downloads a GCS object and returns its content as a base64 string.
 * Returns an error if the object exceeds 20 MB.
 * @param {string} bucket
 * @param {string} object
 * @returns {$CancellablePromise<string>}
 */
export function GetObjectContent(bucket, object) {
    return $Call.ByID(4104387003, bucket, object);
}

/**
 * @param {string} bucket
 * @param {string} object
 * @returns {$CancellablePromise<$models.GCSObjectMetadata | null>}
 */
export function GetObjectMetadata(bucket, object) {
    return $Call.ByID(76473239, bucket, object).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.GCSBucket[]>}
 */
export function ListBuckets(projectID) {
    return $Call.ByID(1867656790, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListCloudRunServices returns all Cloud Run services in the project across all regions.
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.CloudRunService[]>}
 */
export function ListCloudRunServices(projectID) {
    return $Call.ByID(2635577109, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} projectID
 * @param {string} filter
 * @param {string} pageToken
 * @returns {$CancellablePromise<$models.LogPage>}
 */
export function ListLogEntries(projectID, filter, pageToken) {
    return $Call.ByID(1181900761, projectID, filter, pageToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} bucket
 * @param {string} prefix
 * @param {string} pageToken
 * @returns {$CancellablePromise<$models.GCSObjectList>}
 */
export function ListObjects(bucket, prefix, pageToken) {
    return $Call.ByID(4097624265, bucket, prefix, pageToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} projectID
 * @param {string} region
 * @param {string} repoName
 * @returns {$CancellablePromise<$models.ARPackage[]>}
 */
export function ListPackages(projectID, region, repoName) {
    return $Call.ByID(2958372494, projectID, region, repoName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} projectID
 * @param {string} region
 * @returns {$CancellablePromise<$models.ARRepository[]>}
 */
export function ListRepositories(projectID, region) {
    return $Call.ByID(3391911399, projectID, region).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * ListSecretVersions lists versions for a secret. secretResourceName is the full resource name
 * from SMSecret.Name (e.g. "projects/123/secrets/my-secret").
 * @param {string} secretResourceName
 * @returns {$CancellablePromise<$models.SMSecretVersion[]>}
 */
export function ListSecretVersions(secretResourceName) {
    return $Call.ByID(1703252290, secretResourceName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.SMSecret[]>}
 */
export function ListSecrets(projectID) {
    return $Call.ByID(2564033992, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * ListSpannerDatabases lists databases in a Spanner instance.
 * instanceResourceName is the full name e.g. "projects/{project}/instances/{instance}".
 * @param {string} instanceResourceName
 * @returns {$CancellablePromise<$models.SpannerDatabase[]>}
 */
export function ListSpannerDatabases(instanceResourceName) {
    return $Call.ByID(1359586522, instanceResourceName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.SpannerInstance[]>}
 */
export function ListSpannerInstances(projectID) {
    return $Call.ByID(2154481176, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * ListSpannerTables lists tables in a Spanner database by parsing its DDL.
 * databaseResourceName is the full name e.g. "projects/{p}/instances/{i}/databases/{d}".
 * @param {string} databaseResourceName
 * @returns {$CancellablePromise<$models.SpannerTable[]>}
 */
export function ListSpannerTables(databaseResourceName) {
    return $Call.ByID(1954101685, databaseResourceName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * ListVersions lists versions for a package. packageResourceName is the full resource name
 * from ARPackage.Name (e.g. "projects/.../packages/github.com%2Forg%2Fpkg").
 * @param {string} packageResourceName
 * @returns {$CancellablePromise<$models.ARVersion[]>}
 */
export function ListVersions(packageResourceName) {
    return $Call.ByID(2139956354, packageResourceName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * OpenInConsole opens the Google Cloud Console page for the given section in the system browser.
 * resource is optional (e.g. a bucket name for the storage section).
 * @param {string} section
 * @param {string} projectID
 * @param {string} resource
 * @returns {$CancellablePromise<void>}
 */
export function OpenInConsole(section, projectID, resource) {
    return $Call.ByID(1733121933, section, projectID, resource);
}

/**
 * PollSetupOutput returns new terminal output since offset.
 * @param {string} runID
 * @param {number} offset
 * @returns {$CancellablePromise<$models.SetupChunk | null>}
 */
export function PollSetupOutput(runID, offset) {
    return $Call.ByID(16531906, runID, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * ResizeSetupTerminal updates the PTY window size.
 * @param {string} runID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeSetupTerminal(runID, cols, rows) {
    return $Call.ByID(23653932, runID, cols, rows);
}

/**
 * StartSetupSession launches an interactive login shell. If command is non-empty
 * it is sent to the shell after a short delay, exactly like the package terminal.
 * @param {string} runID
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function StartSetupSession(runID, command) {
    return $Call.ByID(2609503366, runID, command);
}

/**
 * StopSetupSession cancels and removes a setup session.
 * @param {string} runID
 * @returns {$CancellablePromise<void>}
 */
export function StopSetupSession(runID) {
    return $Call.ByID(76537976, runID);
}

/**
 * WriteSetupInput forwards keystrokes to the PTY.
 * @param {string} runID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteSetupInput(runID, data) {
    return $Call.ByID(4165421025, runID, data);
}

// Private type creation functions
const $$createType0 = $models.GCloudStatus.createFrom;
const $$createType1 = $models.SpannerDMLResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.SpannerQueryResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.GCSObjectMetadata.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.GCSBucket.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.CloudRunService.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.LogPage.createFrom;
const $$createType12 = $models.GCSObjectList.createFrom;
const $$createType13 = $models.ARPackage.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.ARRepository.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.SMSecretVersion.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $models.SMSecret.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.SpannerDatabase.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $models.SpannerInstance.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.SpannerTable.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $models.ARVersion.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $models.SetupChunk.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
