// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GCloudService exposes GCP REST API tools to the frontend.
 * Auth is via `gcloud auth print-access-token` — cached for 45 minutes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckGCloudStatus reports whether gcloud is installed and can produce a valid
 * access token. It uses print-access-token (not just auth list) so it matches
 * exactly what the API calls require.
 */
export function CheckGCloudStatus(): $CancellablePromise<$models.GCloudStatus> {
    return $Call.ByID(4101128005).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetObjectContent downloads a GCS object and returns its content as a base64 string.
 * Returns an error if the object exceeds 20 MB.
 */
export function GetObjectContent(bucket: string, object: string): $CancellablePromise<string> {
    return $Call.ByID(4104387003, bucket, object);
}

export function GetObjectMetadata(bucket: string, object: string): $CancellablePromise<$models.GCSObjectMetadata | null> {
    return $Call.ByID(76473239, bucket, object).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListBuckets(projectID: string): $CancellablePromise<$models.GCSBucket[]> {
    return $Call.ByID(1867656790, projectID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListLogEntries(projectID: string, filter: string, pageToken: string): $CancellablePromise<$models.LogPage> {
    return $Call.ByID(1181900761, projectID, filter, pageToken).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListObjects(bucket: string, prefix: string, pageToken: string): $CancellablePromise<$models.GCSObjectList> {
    return $Call.ByID(4097624265, bucket, prefix, pageToken).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListPackages(projectID: string, region: string, repoName: string): $CancellablePromise<$models.ARPackage[]> {
    return $Call.ByID(2958372494, projectID, region, repoName).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListRepositories(projectID: string, region: string): $CancellablePromise<$models.ARRepository[]> {
    return $Call.ByID(3391911399, projectID, region).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListSecretVersions lists versions for a secret. secretResourceName is the full resource name
 * from SMSecret.Name (e.g. "projects/123/secrets/my-secret").
 */
export function ListSecretVersions(secretResourceName: string): $CancellablePromise<$models.SMSecretVersion[]> {
    return $Call.ByID(1703252290, secretResourceName).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListSecrets(projectID: string): $CancellablePromise<$models.SMSecret[]> {
    return $Call.ByID(2564033992, projectID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ListVersions lists versions for a package. packageResourceName is the full resource name
 * from ARPackage.Name (e.g. "projects/.../packages/github.com%2Forg%2Fpkg").
 */
export function ListVersions(packageResourceName: string): $CancellablePromise<$models.ARVersion[]> {
    return $Call.ByID(2139956354, packageResourceName).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * OpenInConsole opens the Google Cloud Console page for the given section in the system browser.
 * resource is optional (e.g. a bucket name for the storage section).
 */
export function OpenInConsole(section: string, projectID: string, resource: string): $CancellablePromise<void> {
    return $Call.ByID(1733121933, section, projectID, resource);
}

/**
 * PollSetupOutput returns new terminal output since offset.
 */
export function PollSetupOutput(runID: string, offset: number): $CancellablePromise<$models.SetupChunk | null> {
    return $Call.ByID(16531906, runID, offset).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * ResizeSetupTerminal updates the PTY window size.
 */
export function ResizeSetupTerminal(runID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(23653932, runID, cols, rows);
}

/**
 * StartSetupSession launches an interactive login shell. If command is non-empty
 * it is sent to the shell after a short delay, exactly like the package terminal.
 */
export function StartSetupSession(runID: string, command: string): $CancellablePromise<void> {
    return $Call.ByID(2609503366, runID, command);
}

/**
 * StopSetupSession cancels and removes a setup session.
 */
export function StopSetupSession(runID: string): $CancellablePromise<void> {
    return $Call.ByID(76537976, runID);
}

/**
 * WriteSetupInput forwards keystrokes to the PTY.
 */
export function WriteSetupInput(runID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(4165421025, runID, data);
}

// Private type creation functions
const $$createType0 = $models.GCloudStatus.createFrom;
const $$createType1 = $models.GCSObjectMetadata.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.GCSBucket.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.LogPage.createFrom;
const $$createType6 = $models.GCSObjectList.createFrom;
const $$createType7 = $models.ARPackage.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.ARRepository.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.SMSecretVersion.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.SMSecret.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.ARVersion.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.SetupChunk.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
