// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService provides local git operations for the block merge flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortMerge aborts an in-progress merge.
 */
export function AbortMerge(repoPath: string): $CancellablePromise<void> {
    return $Call.ByID(6565443, repoPath);
}

/**
 * AddPRComment posts a new comment on a pull request and returns the created comment.
 */
export function AddPRComment(repoPath: string, $number: number, body: string): $CancellablePromise<$models.PRComment | null> {
    return $Call.ByID(1202741783, repoPath, $number, body).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckoutBranch switches to an existing branch and returns a classified result.
 */
export function CheckoutBranch(repoPath: string, branchName: string): $CancellablePromise<$models.GitSyncResult> {
    return $Call.ByID(3127373489, repoPath, branchName).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Commit creates a commit with the given message.
 */
export function Commit(repoPath: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(471482348, repoPath, message);
}

/**
 * CompleteMerge finalises the merge with a commit (non-interactive).
 */
export function CompleteMerge(repoPath: string): $CancellablePromise<void> {
    return $Call.ByID(4202278426, repoPath);
}

/**
 * CreateBranch creates and switches to a new branch.
 */
export function CreateBranch(repoPath: string, branchName: string): $CancellablePromise<void> {
    return $Call.ByID(301706189, repoPath, branchName);
}

/**
 * CreatePR creates a new pull request. head and base are branch names.
 */
export function CreatePR(repoPath: string, title: string, body: string, head: string, base: string): $CancellablePromise<$models.ForgejoPR | null> {
    return $Call.ByID(1421252495, repoPath, title, body, head, base).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * DiscardFile discards working tree changes for a file.
 */
export function DiscardFile(repoPath: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(3427842007, repoPath, filePath);
}

/**
 * FetchOrigin fetches from origin (updating remote-tracking refs and ahead/behind
 * state) without touching the working tree or local branch. Used both for manual
 * refresh and periodic background polling.
 */
export function FetchOrigin(repoPath: string): $CancellablePromise<$models.GitSyncResult> {
    return $Call.ByID(3365636253, repoPath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAheadBehind returns how many commits the current branch is ahead/behind its upstream.
 * Returns zeros when no upstream is configured or when the comparison fails.
 */
export function GetAheadBehind(repoPath: string): $CancellablePromise<$models.AheadBehind | null> {
    return $Call.ByID(1150452256, repoPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetBranchCommitCount returns how many commits head has that base does not,
 * comparing the remote tracking refs (origin/head vs origin/base).
 * Returns 0 when the refs don't exist or the branches are already in sync.
 */
export function GetBranchCommitCount(repoPath: string, head: string, base: string): $CancellablePromise<number> {
    return $Call.ByID(3871857613, repoPath, head, base);
}

/**
 * GetBranches returns all local and remote branches.
 */
export function GetBranches(repoPath: string): $CancellablePromise<$models.GitBranch[]> {
    return $Call.ByID(3919711711, repoPath).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetCommitFileDiff returns the diff for a single file within a specific commit.
 */
export function GetCommitFileDiff(repoPath: string, hash: string, filePath: string): $CancellablePromise<$models.GitFileDiff | null> {
    return $Call.ByID(2802220399, repoPath, hash, filePath).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetCommitFiles returns the list of files changed by a specific commit.
 */
export function GetCommitFiles(repoPath: string, hash: string): $CancellablePromise<$models.CommitFile[]> {
    return $Call.ByID(434630353, repoPath, hash).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetConflictContent reads a conflicted file and parses its conflict hunks.
 */
export function GetConflictContent(repoPath: string, filePath: string): $CancellablePromise<$models.ConflictFileContent | null> {
    return $Call.ByID(2044518434, repoPath, filePath).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetConflictFiles returns the list of files with unmerged conflicts.
 */
export function GetConflictFiles(repoPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(652532720, repoPath).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetCurrentBranch returns the name of the currently checked-out branch.
 */
export function GetCurrentBranch(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(2144274600, repoPath);
}

/**
 * GetFileDiff returns old and new file content plus diff hunks for the diff viewer.
 * staged=true shows index vs HEAD; staged=false shows working tree vs index.
 */
export function GetFileDiff(repoPath: string, filePath: string, staged: boolean): $CancellablePromise<$models.GitFileDiff | null> {
    return $Call.ByID(1333579366, repoPath, filePath, staged).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetLog returns commit history for the git graph.
 */
export function GetLog(repoPath: string, limit: number): $CancellablePromise<$models.GitCommit[]> {
    return $Call.ByID(1590913447, repoPath, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetPRComments returns the conversation comments on a pull request.
 */
export function GetPRComments(repoPath: string, $number: number): $CancellablePromise<$models.PRComment[]> {
    return $Call.ByID(1666356855, repoPath, $number).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetPRCommits returns the list of commits included in a pull request.
 */
export function GetPRCommits(repoPath: string, $number: number): $CancellablePromise<$models.PRCommit[]> {
    return $Call.ByID(1353400125, repoPath, $number).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * GetPRFileDiff returns the diff for a single file across the PR's head vs base branches.
 * Uses a three-dot diff: git diff origin/{base}...origin/{head} -- {filePath}
 */
export function GetPRFileDiff(repoPath: string, baseBranch: string, headBranch: string, filePath: string): $CancellablePromise<$models.GitFileDiff | null> {
    return $Call.ByID(276206784, repoPath, baseBranch, headBranch, filePath).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetPRFiles returns the list of files changed in a pull request.
 */
export function GetPRFiles(repoPath: string, $number: number): $CancellablePromise<$models.CommitFile[]> {
    return $Call.ByID(2369629616, repoPath, $number).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetProductRepoPaths returns the local build and define repo paths for the given product.
 * org and product are short names (e.g. "voyage", "vp").
 */
export function GetProductRepoPaths(org: string, product: string): $CancellablePromise<$models.ProductRepoPaths | null> {
    return $Call.ByID(674422590, org, product).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * GetStatus returns staged, unstaged, and untracked file lists.
 */
export function GetStatus(repoPath: string): $CancellablePromise<$models.GitStatus | null> {
    return $Call.ByID(2522644849, repoPath).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * IsForgejo returns true if the repo's origin remote is a Forgejo host.
 */
export function IsForgejo(repoPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(2168993683, repoPath);
}

/**
 * ListPRs returns pull requests for the given repo. state is "open", "closed", or "all".
 */
export function ListPRs(repoPath: string, state: string): $CancellablePromise<$models.ForgejoPR[]> {
    return $Call.ByID(365587936, repoPath, state).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * MergePR merges a pull request. mergeStyle is "merge", "rebase", or "squash".
 */
export function MergePR(repoPath: string, $number: number, mergeStyle: string): $CancellablePromise<void> {
    return $Call.ByID(2365324437, repoPath, $number, mergeStyle);
}

/**
 * PullOrigin pulls the current branch from origin and returns a classified result.
 * For pull_conflict, ConflictFiles is populated.
 */
export function PullOrigin(repoPath: string): $CancellablePromise<$models.GitSyncResult> {
    return $Call.ByID(1482641752, repoPath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * PushOrigin pushes the current branch to origin and returns a classified result.
 */
export function PushOrigin(repoPath: string): $CancellablePromise<$models.GitSyncResult> {
    return $Call.ByID(3747123927, repoPath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveConflictResolution replaces each conflict marker block in the file with the
 * corresponding resolved lines (one entry per hunk, in order), writes the file, and
 * stages it with git add. resolutions[i] is the newline-joined content for hunk i.
 */
export function SaveConflictResolution(repoPath: string, filePath: string, resolutions: string[]): $CancellablePromise<void> {
    return $Call.ByID(1423658464, repoPath, filePath, resolutions);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1890383270, app);
}

/**
 * StageAll stages all changes.
 */
export function StageAll(repoPath: string): $CancellablePromise<void> {
    return $Call.ByID(4059387404, repoPath);
}

/**
 * StageFile stages a single file.
 */
export function StageFile(repoPath: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(4185947995, repoPath, filePath);
}

/**
 * StageFiles stages multiple files in a single git invocation, avoiding the
 * .git/index.lock race that firing one StageFile call per path concurrently
 * would cause.
 */
export function StageFiles(repoPath: string, paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3980930040, repoPath, paths);
}

/**
 * StartRemoteMerge merges branchName into baseBranch on the Forgejo remote via a
 * pull request (opening one if none exists yet, reusing it otherwise), then
 * fast-forwards the local clone. The merge itself happens server-side — the local
 * working tree is never put into a mid-merge state, matching how a user would merge
 * the block branch manually on the git host before pulling the base branch locally.
 * baseBranch defaults to "master" when empty (the common case for a define repo,
 * which typically only has one long-lived branch; build repos can have several,
 * so callers should let the user pick).
 * Git command output is streamed via "git:log" Wails events.
 */
export function StartRemoteMerge(repoPath: string, branchName: string, baseBranch: string): $CancellablePromise<$models.RemoteMergeResult | null> {
    return $Call.ByID(1529596895, repoPath, branchName, baseBranch).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * UndoLastCommit soft-resets HEAD by one commit, leaving the undone commit's
 * changes staged. Purely local — callers are expected to only allow this when
 * the commit hasn't been pushed yet (see GetAheadBehind).
 */
export function UndoLastCommit(repoPath: string): $CancellablePromise<$models.GitSyncResult> {
    return $Call.ByID(3830717270, repoPath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * UnstageFile removes a file from the staging area.
 */
export function UnstageFile(repoPath: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(3130933074, repoPath, filePath);
}

/**
 * UnstageFiles removes multiple files from the staging area in a single git
 * invocation, avoiding the .git/index.lock race of concurrent per-file calls.
 */
export function UnstageFiles(repoPath: string, paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3894239475, repoPath, paths);
}

/**
 * WatchRepo begins watching repoPath/.git for external changes.
 * Idempotent — safe to call multiple times for the same path.
 */
export function WatchRepo(repoPath: string): $CancellablePromise<void> {
    return $Call.ByID(422539044, repoPath);
}

// Private type creation functions
const $$createType0 = $models.PRComment.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.GitSyncResult.createFrom;
const $$createType3 = $models.ForgejoPR.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.AheadBehind.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.GitBranch.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.GitFileDiff.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.CommitFile.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.ConflictFileContent.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = $models.GitCommit.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($$createType0);
const $$createType19 = $models.PRCommit.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.ProductRepoPaths.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $models.GitStatus.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $Create.Array($$createType3);
const $$createType26 = $models.RemoteMergeResult.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
