// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitService provides local git operations for the block merge flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortMerge aborts an in-progress merge.
 */
export function AbortMerge(repoPath: string): $CancellablePromise<void> {
    return $Call.ByID(6565443, repoPath);
}

/**
 * AddPRComment posts a new comment on a pull request and returns the created comment.
 */
export function AddPRComment(repoPath: string, $number: number, body: string): $CancellablePromise<$models.PRComment | null> {
    return $Call.ByID(1202741783, repoPath, $number, body).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CheckoutBranch switches to an existing branch.
 */
export function CheckoutBranch(repoPath: string, branchName: string): $CancellablePromise<void> {
    return $Call.ByID(3127373489, repoPath, branchName);
}

/**
 * Commit creates a commit with the given message.
 */
export function Commit(repoPath: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(471482348, repoPath, message);
}

/**
 * CompleteMerge finalises the merge with a commit (non-interactive).
 */
export function CompleteMerge(repoPath: string): $CancellablePromise<void> {
    return $Call.ByID(4202278426, repoPath);
}

/**
 * CreateBranch creates and switches to a new branch.
 */
export function CreateBranch(repoPath: string, branchName: string): $CancellablePromise<void> {
    return $Call.ByID(301706189, repoPath, branchName);
}

/**
 * CreatePR creates a new pull request. head and base are branch names.
 */
export function CreatePR(repoPath: string, title: string, body: string, head: string, base: string): $CancellablePromise<$models.ForgejoPR | null> {
    return $Call.ByID(1421252495, repoPath, title, body, head, base).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DiscardFile discards working tree changes for a file.
 */
export function DiscardFile(repoPath: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(3427842007, repoPath, filePath);
}

/**
 * GetAheadBehind returns how many commits the current branch is ahead/behind its upstream.
 * Returns zeros when no upstream is configured or when the comparison fails.
 */
export function GetAheadBehind(repoPath: string): $CancellablePromise<$models.AheadBehind | null> {
    return $Call.ByID(1150452256, repoPath).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetBranches returns all local and remote branches.
 */
export function GetBranches(repoPath: string): $CancellablePromise<$models.GitBranch[]> {
    return $Call.ByID(3919711711, repoPath).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetCommitFileDiff returns the diff for a single file within a specific commit.
 */
export function GetCommitFileDiff(repoPath: string, hash: string, filePath: string): $CancellablePromise<$models.GitFileDiff | null> {
    return $Call.ByID(2802220399, repoPath, hash, filePath).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetCommitFiles returns the list of files changed by a specific commit.
 */
export function GetCommitFiles(repoPath: string, hash: string): $CancellablePromise<$models.CommitFile[]> {
    return $Call.ByID(434630353, repoPath, hash).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetConflictContent reads a conflicted file and parses its conflict hunks.
 */
export function GetConflictContent(repoPath: string, filePath: string): $CancellablePromise<$models.ConflictFileContent | null> {
    return $Call.ByID(2044518434, repoPath, filePath).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetConflictFiles returns the list of files with unmerged conflicts.
 */
export function GetConflictFiles(repoPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(652532720, repoPath).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetCurrentBranch returns the name of the currently checked-out branch.
 */
export function GetCurrentBranch(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(2144274600, repoPath);
}

/**
 * GetFileDiff returns old and new file content plus diff hunks for the diff viewer.
 * staged=true shows index vs HEAD; staged=false shows working tree vs index.
 */
export function GetFileDiff(repoPath: string, filePath: string, staged: boolean): $CancellablePromise<$models.GitFileDiff | null> {
    return $Call.ByID(1333579366, repoPath, filePath, staged).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetLog returns commit history for the git graph.
 */
export function GetLog(repoPath: string, limit: number): $CancellablePromise<$models.GitCommit[]> {
    return $Call.ByID(1590913447, repoPath, limit).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GetPRComments returns the conversation comments on a pull request.
 */
export function GetPRComments(repoPath: string, $number: number): $CancellablePromise<$models.PRComment[]> {
    return $Call.ByID(1666356855, repoPath, $number).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetPRCommits returns the list of commits included in a pull request.
 */
export function GetPRCommits(repoPath: string, $number: number): $CancellablePromise<$models.PRCommit[]> {
    return $Call.ByID(1353400125, repoPath, $number).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetPRFileDiff returns the diff for a single file across the PR's head vs base branches.
 * Uses a three-dot diff: git diff origin/{base}...origin/{head} -- {filePath}
 */
export function GetPRFileDiff(repoPath: string, baseBranch: string, headBranch: string, filePath: string): $CancellablePromise<$models.GitFileDiff | null> {
    return $Call.ByID(276206784, repoPath, baseBranch, headBranch, filePath).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetPRFiles returns the list of files changed in a pull request.
 */
export function GetPRFiles(repoPath: string, $number: number): $CancellablePromise<$models.CommitFile[]> {
    return $Call.ByID(2369629616, repoPath, $number).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetProductRepoPaths returns the local build and define repo paths for the given product.
 * org and product are short names (e.g. "voyage", "vp").
 */
export function GetProductRepoPaths(org: string, product: string): $CancellablePromise<$models.ProductRepoPaths | null> {
    return $Call.ByID(674422590, org, product).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * GetStatus returns staged, unstaged, and untracked file lists.
 */
export function GetStatus(repoPath: string): $CancellablePromise<$models.GitStatus | null> {
    return $Call.ByID(2522644849, repoPath).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * IsForgejo returns true if the repo's origin remote is a Forgejo host.
 */
export function IsForgejo(repoPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(2168993683, repoPath);
}

/**
 * ListPRs returns pull requests for the given repo. state is "open", "closed", or "all".
 */
export function ListPRs(repoPath: string, state: string): $CancellablePromise<$models.ForgejoPR[]> {
    return $Call.ByID(365587936, repoPath, state).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * MergePR merges a pull request. mergeStyle is "merge", "rebase", or "squash".
 */
export function MergePR(repoPath: string, $number: number, mergeStyle: string): $CancellablePromise<void> {
    return $Call.ByID(2365324437, repoPath, $number, mergeStyle);
}

/**
 * PullOrigin pulls the current branch from origin and returns a classified result.
 * For pull_conflict, ConflictFiles is populated.
 */
export function PullOrigin(repoPath: string): $CancellablePromise<$models.GitSyncResult> {
    return $Call.ByID(1482641752, repoPath).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * PushOrigin pushes the current branch to origin and returns a classified result.
 */
export function PushOrigin(repoPath: string): $CancellablePromise<$models.GitSyncResult> {
    return $Call.ByID(3747123927, repoPath).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * SaveConflictResolution replaces each conflict marker block in the file with the
 * corresponding resolved lines (one entry per hunk, in order), writes the file, and
 * stages it with git add. resolutions[i] is the newline-joined content for hunk i.
 */
export function SaveConflictResolution(repoPath: string, filePath: string, resolutions: string[]): $CancellablePromise<void> {
    return $Call.ByID(1423658464, repoPath, filePath, resolutions);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1890383270, app);
}

/**
 * StageAll stages all changes.
 */
export function StageAll(repoPath: string): $CancellablePromise<void> {
    return $Call.ByID(4059387404, repoPath);
}

/**
 * StageFile stages a single file.
 */
export function StageFile(repoPath: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(4185947995, repoPath, filePath);
}

/**
 * StartLocalMerge runs: git fetch, checkout master, pull, then merge origin/{branchName}.
 * Returns conflict file list if exit code 1 (conflicts detected).
 * Git command output is streamed via "git:log" Wails events.
 */
export function StartLocalMerge(repoPath: string, branchName: string): $CancellablePromise<$models.LocalMergeResult | null> {
    return $Call.ByID(2277677406, repoPath, branchName).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * UnstageFile removes a file from the staging area.
 */
export function UnstageFile(repoPath: string, filePath: string): $CancellablePromise<void> {
    return $Call.ByID(3130933074, repoPath, filePath);
}

/**
 * WatchRepo begins watching repoPath/.git for external changes.
 * Idempotent — safe to call multiple times for the same path.
 */
export function WatchRepo(repoPath: string): $CancellablePromise<void> {
    return $Call.ByID(422539044, repoPath);
}

// Private type creation functions
const $$createType0 = $models.PRComment.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ForgejoPR.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.AheadBehind.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GitBranch.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.GitFileDiff.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.CommitFile.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.ConflictFileContent.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = $models.GitCommit.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $Create.Array($$createType0);
const $$createType18 = $models.PRCommit.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.ProductRepoPaths.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $models.GitStatus.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $Create.Array($$createType2);
const $$createType25 = $models.GitSyncResult.createFrom;
const $$createType26 = $models.LocalMergeResult.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
