// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalAIService integrates with a locally-managed Ollama instance for
 * on-device LLM inference (commit message generation, smart suggestions).
 * The app downloads the Ollama binary and manages its lifecycle — no
 * external installation is required from the user.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckOllama returns true if an Ollama instance is reachable at the default address.
 */
export function CheckOllama(): $CancellablePromise<boolean> {
    return $Call.ByID(4138256558);
}

/**
 * DownloadOllamaBinary downloads the Ollama binary for the current platform.
 * It runs asynchronously and emits progress events:
 * 
 * 	localai:ollama-download-progress { pct int, label string }
 * 	localai:ollama-download-done
 * 	localai:ollama-download-error { error string }
 */
export function DownloadOllamaBinary(): $CancellablePromise<void> {
    return $Call.ByID(516605903);
}

/**
 * Generate calls Ollama's generate endpoint synchronously and returns the response text.
 */
export function Generate(model: string, systemPrompt: string, userPrompt: string): $CancellablePromise<string> {
    return $Call.ByID(47512519, model, systemPrompt, userPrompt);
}

/**
 * GenerateCommitMessage generates a conventional commit message from the current staged diff in repoPath.
 */
export function GenerateCommitMessage(repoPath: string, model: string): $CancellablePromise<string> {
    return $Call.ByID(747920221, repoPath, model);
}

/**
 * GetOllamaStatus returns whether the binary is on disk and whether the API is responding.
 */
export function GetOllamaStatus(): $CancellablePromise<$models.OllamaStatus> {
    return $Call.ByID(596840604).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetPulledModels returns the names of all models currently available in Ollama.
 */
export function GetPulledModels(): $CancellablePromise<string[]> {
    return $Call.ByID(3598413308).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PullModel starts an async model download and emits progress events:
 * 
 * 	localai:pull-progress  { status, completed, total }
 * 	localai:pull-done      (no payload)
 * 	localai:pull-error     { error }
 */
export function PullModel(model: string): $CancellablePromise<void> {
    return $Call.ByID(2099708404, model);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3877976915, app);
}

/**
 * StartOllama starts the managed Ollama subprocess if it isn't already running.
 * Returns an error if the process fails to start or doesn't become ready within 10 seconds.
 */
export function StartOllama(): $CancellablePromise<void> {
    return $Call.ByID(825124690);
}

/**
 * StopOllama terminates the managed Ollama subprocess.
 */
export function StopOllama(): $CancellablePromise<void> {
    return $Call.ByID(1041252718);
}

// Private type creation functions
const $$createType0 = $models.OllamaStatus.createFrom;
const $$createType1 = $Create.Array($Create.Any);
