// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ARPackage {
    "name": string;
    "displayName": string;
    "createTime": string;
    "updateTime": string;

    /** Creates a new ARPackage instance. */
    constructor($$source: Partial<ARPackage> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = "";
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ARPackage instance from a string or object.
     */
    static createFrom($$source: any = {}): ARPackage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ARPackage($$parsedSource as Partial<ARPackage>);
    }
}

export class ARRepository {
    "name": string;
    "format": string;
    "description": string;
    "createTime": string;

    /** Creates a new ARRepository instance. */
    constructor($$source: Partial<ARRepository> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ARRepository instance from a string or object.
     */
    static createFrom($$source: any = {}): ARRepository {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ARRepository($$parsedSource as Partial<ARRepository>);
    }
}

export class ARVersion {
    "name": string;
    "createTime": string;
    "updateTime": string;

    /** Creates a new ARVersion instance. */
    constructor($$source: Partial<ARVersion> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = "";
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ARVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): ARVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ARVersion($$parsedSource as Partial<ARVersion>);
    }
}

/**
 * BuildLogsResult is returned by FetchBuildLogs.
 * NextOffset is the character count of all log text seen so far; pass it back on the
 * next call so only newly-appended lines are returned.
 */
export class BuildLogsResult {
    "content": string;
    "nextOffset": number;

    /** Creates a new BuildLogsResult instance. */
    constructor($$source: Partial<BuildLogsResult> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("nextOffset" in $$source)) {
            this["nextOffset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildLogsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildLogsResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuildLogsResult($$parsedSource as Partial<BuildLogsResult>);
    }
}

/**
 * BuildSpecItem is a summary of a single build specification.
 */
export class BuildSpecItem {
    "name": string;
    "displayName": string;

    /**
     * 0=unspecified, 1=new, 2=active, 3=completed
     */
    "status": number;
    "summary": string;

    /**
     * resource names: organisations/{org}/products/{product}
     */
    "products": string[];

    /** Creates a new BuildSpecItem instance. */
    constructor($$source: Partial<BuildSpecItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("products" in $$source)) {
            this["products"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildSpecItem instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildSpecItem {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("products" in $$parsedSource) {
            $$parsedSource["products"] = $$createField4_0($$parsedSource["products"]);
        }
        return new BuildSpecItem($$parsedSource as Partial<BuildSpecItem>);
    }
}

export class Codeblock {
    "name": string;
    "displayName": string;
    "releaseLevel": number;
    "publisher": string;
    "latestVersion": string;
    "headline": string;
    "description": string;
    "bannerUrl": string;
    "installCount": number;

    /** Creates a new Codeblock instance. */
    constructor($$source: Partial<Codeblock> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("releaseLevel" in $$source)) {
            this["releaseLevel"] = 0;
        }
        if (!("publisher" in $$source)) {
            this["publisher"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("headline" in $$source)) {
            this["headline"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("bannerUrl" in $$source)) {
            this["bannerUrl"] = "";
        }
        if (!("installCount" in $$source)) {
            this["installCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Codeblock instance from a string or object.
     */
    static createFrom($$source: any = {}): Codeblock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Codeblock($$parsedSource as Partial<Codeblock>);
    }
}

/**
 * DefineCommit represents a git commit in the define repository.
 */
export class DefineCommit {
    "sha": string;
    "message": string;
    "author": string;
    "authorEmail": string;
    "timestamp": number;

    /** Creates a new DefineCommit instance. */
    constructor($$source: Partial<DefineCommit> = {}) {
        if (!("sha" in $$source)) {
            this["sha"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            this["authorEmail"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DefineCommit instance from a string or object.
     */
    static createFrom($$source: any = {}): DefineCommit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DefineCommit($$parsedSource as Partial<DefineCommit>);
    }
}

/**
 * DeployItem is a single deployment entry returned from the backend.
 */
export class DeployItem {
    "logsUrl": string;

    /** Creates a new DeployItem instance. */
    constructor($$source: Partial<DeployItem> = {}) {
        if (!("logsUrl" in $$source)) {
            this["logsUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DeployItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeployItem($$parsedSource as Partial<DeployItem>);
    }
}

export class DeploymentItem {
    "neuronId": string;
    "version": string;
    "state": number;
    "logsUrl": string;

    /** Creates a new DeploymentItem instance. */
    constructor($$source: Partial<DeploymentItem> = {}) {
        if (!("neuronId" in $$source)) {
            this["neuronId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("logsUrl" in $$source)) {
            this["logsUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DeploymentItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeploymentItem($$parsedSource as Partial<DeploymentItem>);
    }
}

export class EnvDeployments {
    "name": string;
    "displayName": string;
    "deployments": DeploymentItem[];

    /** Creates a new EnvDeployments instance. */
    constructor($$source: Partial<EnvDeployments> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("deployments" in $$source)) {
            this["deployments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvDeployments instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvDeployments {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deployments" in $$parsedSource) {
            $$parsedSource["deployments"] = $$createField2_0($$parsedSource["deployments"]);
        }
        return new EnvDeployments($$parsedSource as Partial<EnvDeployments>);
    }
}

export class EnvInfo {
    "name": string;
    "displayName": string;
    "state": number;
    "gcpProject"?: GCPProject | null;

    /** Creates a new EnvInfo instance. */
    constructor($$source: Partial<EnvInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvInfo {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("gcpProject" in $$parsedSource) {
            $$parsedSource["gcpProject"] = $$createField3_0($$parsedSource["gcpProject"]);
        }
        return new EnvInfo($$parsedSource as Partial<EnvInfo>);
    }
}

export class EnvVariable {
    "label": string;
    "value": string;

    /** Creates a new EnvVariable instance. */
    constructor($$source: Partial<EnvVariable> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvVariable instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvVariable {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvVariable($$parsedSource as Partial<EnvVariable>);
    }
}

export class GCPProject {
    "folderId": string;
    "id": string;
    "number": string;
    "region": string;
    "billingAccountId": string;
    "managedBillingAccount": boolean;
    "cloudUri": string;

    /** Creates a new GCPProject instance. */
    constructor($$source: Partial<GCPProject> = {}) {
        if (!("folderId" in $$source)) {
            this["folderId"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("billingAccountId" in $$source)) {
            this["billingAccountId"] = "";
        }
        if (!("managedBillingAccount" in $$source)) {
            this["managedBillingAccount"] = false;
        }
        if (!("cloudUri" in $$source)) {
            this["cloudUri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GCPProject instance from a string or object.
     */
    static createFrom($$source: any = {}): GCPProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GCPProject($$parsedSource as Partial<GCPProject>);
    }
}

export class GCSBucket {
    "name": string;
    "location": string;
    "storageClass": string;
    "timeCreated": string;

    /** Creates a new GCSBucket instance. */
    constructor($$source: Partial<GCSBucket> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("location" in $$source)) {
            this["location"] = "";
        }
        if (!("storageClass" in $$source)) {
            this["storageClass"] = "";
        }
        if (!("timeCreated" in $$source)) {
            this["timeCreated"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GCSBucket instance from a string or object.
     */
    static createFrom($$source: any = {}): GCSBucket {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GCSBucket($$parsedSource as Partial<GCSBucket>);
    }
}

export class GCSObject {
    "name": string;
    "size": string;
    "contentType": string;
    "updated": string;

    /** Creates a new GCSObject instance. */
    constructor($$source: Partial<GCSObject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = "";
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("updated" in $$source)) {
            this["updated"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GCSObject instance from a string or object.
     */
    static createFrom($$source: any = {}): GCSObject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GCSObject($$parsedSource as Partial<GCSObject>);
    }
}

export class GCSObjectList {
    "prefixes": string[];
    "items": GCSObject[];
    "nextPageToken": string;

    /** Creates a new GCSObjectList instance. */
    constructor($$source: Partial<GCSObjectList> = {}) {
        if (!("prefixes" in $$source)) {
            this["prefixes"] = [];
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("nextPageToken" in $$source)) {
            this["nextPageToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GCSObjectList instance from a string or object.
     */
    static createFrom($$source: any = {}): GCSObjectList {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prefixes" in $$parsedSource) {
            $$parsedSource["prefixes"] = $$createField0_0($$parsedSource["prefixes"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new GCSObjectList($$parsedSource as Partial<GCSObjectList>);
    }
}

export class GCloudStatus {
    "gcloudInstalled": boolean;
    "gcloudPath"?: string;
    "authenticated": boolean;
    "authAccount"?: string;

    /** Creates a new GCloudStatus instance. */
    constructor($$source: Partial<GCloudStatus> = {}) {
        if (!("gcloudInstalled" in $$source)) {
            this["gcloudInstalled"] = false;
        }
        if (!("authenticated" in $$source)) {
            this["authenticated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GCloudStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GCloudStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GCloudStatus($$parsedSource as Partial<GCloudStatus>);
    }
}

export class GitRepoInfo {
    "remoteUri": string;
    "cloudRunUri": string;
    "vmUri": string;
    "bucketUri": string;

    /** Creates a new GitRepoInfo instance. */
    constructor($$source: Partial<GitRepoInfo> = {}) {
        if (!("remoteUri" in $$source)) {
            this["remoteUri"] = "";
        }
        if (!("cloudRunUri" in $$source)) {
            this["cloudRunUri"] = "";
        }
        if (!("vmUri" in $$source)) {
            this["vmUri"] = "";
        }
        if (!("bucketUri" in $$source)) {
            this["bucketUri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitRepoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GitRepoInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitRepoInfo($$parsedSource as Partial<GitRepoInfo>);
    }
}

/**
 * GlassArtifact is one artifact type from ExplainDefine.
 */
export class GlassArtifact {
    "type": string;
    "state": number;
    "notes": string;
    "locationUri": string;

    /**
     * packageImportPath (Go) or packageName (JS)
     */
    "extra": string;

    /** Creates a new GlassArtifact instance. */
    constructor($$source: Partial<GlassArtifact> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("locationUri" in $$source)) {
            this["locationUri"] = "";
        }
        if (!("extra" in $$source)) {
            this["extra"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassArtifact instance from a string or object.
     */
    static createFrom($$source: any = {}): GlassArtifact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlassArtifact($$parsedSource as Partial<GlassArtifact>);
    }
}

/**
 * GlassDefinition holds current definition metadata from ExplainDefine.
 */
export class GlassDefinition {
    "name": string;
    "version": string;
    "commit": string;
    "releaseType": string;

    /** Creates a new GlassDefinition instance. */
    constructor($$source: Partial<GlassDefinition> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("releaseType" in $$source)) {
            this["releaseType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): GlassDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlassDefinition($$parsedSource as Partial<GlassDefinition>);
    }
}

/**
 * GlassResult is the response from ExplainDefine.
 */
export class GlassResult {
    "title": string;
    "summary": string;
    "definition": GlassDefinition;
    "artifacts": GlassArtifact[];

    /** Creates a new GlassResult instance. */
    constructor($$source: Partial<GlassResult> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = (new GlassDefinition());
        }
        if (!("artifacts" in $$source)) {
            this["artifacts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GlassResult {
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definition" in $$parsedSource) {
            $$parsedSource["definition"] = $$createField2_0($$parsedSource["definition"]);
        }
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField3_0($$parsedSource["artifacts"]);
        }
        return new GlassResult($$parsedSource as Partial<GlassResult>);
    }
}

export class InviteInfo {
    "name": string;
    "buildSeat": number;
    "manageSeat": number;
    "allowAll": boolean;
    "domains": string[];
    "users": InviteUserInfo[];
    "inviter": string;

    /** Creates a new InviteInfo instance. */
    constructor($$source: Partial<InviteInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("buildSeat" in $$source)) {
            this["buildSeat"] = 0;
        }
        if (!("manageSeat" in $$source)) {
            this["manageSeat"] = 0;
        }
        if (!("allowAll" in $$source)) {
            this["allowAll"] = false;
        }
        if (!("domains" in $$source)) {
            this["domains"] = [];
        }
        if (!("users" in $$source)) {
            this["users"] = [];
        }
        if (!("inviter" in $$source)) {
            this["inviter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InviteInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): InviteInfo {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("domains" in $$parsedSource) {
            $$parsedSource["domains"] = $$createField4_0($$parsedSource["domains"]);
        }
        if ("users" in $$parsedSource) {
            $$parsedSource["users"] = $$createField5_0($$parsedSource["users"]);
        }
        return new InviteInfo($$parsedSource as Partial<InviteInfo>);
    }
}

export class InviteUserInfo {
    "user": string;
    "email": string;
    "displayName": string;
    "profilePicture": string;
    "domain": string;
    "claimed": boolean;
    "role": number;

    /** Creates a new InviteUserInfo instance. */
    constructor($$source: Partial<InviteUserInfo> = {}) {
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("profilePicture" in $$source)) {
            this["profilePicture"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("claimed" in $$source)) {
            this["claimed"] = false;
        }
        if (!("role" in $$source)) {
            this["role"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InviteUserInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): InviteUserInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InviteUserInfo($$parsedSource as Partial<InviteUserInfo>);
    }
}

export class LandingZonesData {
    "own": Organisation[];
    "shared": Organisation[];

    /** Creates a new LandingZonesData instance. */
    constructor($$source: Partial<LandingZonesData> = {}) {
        if (!("own" in $$source)) {
            this["own"] = [];
        }
        if (!("shared" in $$source)) {
            this["shared"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LandingZonesData instance from a string or object.
     */
    static createFrom($$source: any = {}): LandingZonesData {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("own" in $$parsedSource) {
            $$parsedSource["own"] = $$createField0_0($$parsedSource["own"]);
        }
        if ("shared" in $$parsedSource) {
            $$parsedSource["shared"] = $$createField1_0($$parsedSource["shared"]);
        }
        return new LandingZonesData($$parsedSource as Partial<LandingZonesData>);
    }
}

/**
 * LocalBuildChunk is a polling response for a running local Docker build.
 */
export class LocalBuildChunk {
    "content": string;
    "nextOffset": number;
    "done": boolean;
    "error"?: string;

    /** Creates a new LocalBuildChunk instance. */
    constructor($$source: Partial<LocalBuildChunk> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("nextOffset" in $$source)) {
            this["nextOffset"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalBuildChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalBuildChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalBuildChunk($$parsedSource as Partial<LocalBuildChunk>);
    }
}

/**
 * LocalBuildResult is returned when a local Docker build is started.
 */
export class LocalBuildResult {
    "buildId": string;

    /** Creates a new LocalBuildResult instance. */
    constructor($$source: Partial<LocalBuildResult> = {}) {
        if (!("buildId" in $$source)) {
            this["buildId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalBuildResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalBuildResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalBuildResult($$parsedSource as Partial<LocalBuildResult>);
    }
}

export class LogEntry {
    "logName": string;
    "insertId": string;
    "timestamp": string;
    "severity": string;
    "textPayload"?: string;
    "resource"?: LogResource | null;
    "labels"?: { [_ in string]?: string };
    "jsonPayload"?: { [_ in string]?: any };

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("logName" in $$source)) {
            this["logName"] = "";
        }
        if (!("insertId" in $$source)) {
            this["insertId"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType16;
        const $$createField7_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resource" in $$parsedSource) {
            $$parsedSource["resource"] = $$createField5_0($$parsedSource["resource"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField6_0($$parsedSource["labels"]);
        }
        if ("jsonPayload" in $$parsedSource) {
            $$parsedSource["jsonPayload"] = $$createField7_0($$parsedSource["jsonPayload"]);
        }
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class LogPage {
    "entries": LogEntry[];
    "nextPageToken": string;

    /** Creates a new LogPage instance. */
    constructor($$source: Partial<LogPage> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("nextPageToken" in $$source)) {
            this["nextPageToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogPage instance from a string or object.
     */
    static createFrom($$source: any = {}): LogPage {
        const $$createField0_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new LogPage($$parsedSource as Partial<LogPage>);
    }
}

export class LogResource {
    "type": string;
    "labels": { [_ in string]?: string };

    /** Creates a new LogResource instance. */
    constructor($$source: Partial<LogResource> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogResource instance from a string or object.
     */
    static createFrom($$source: any = {}): LogResource {
        const $$createField1_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField1_0($$parsedSource["labels"]);
        }
        return new LogResource($$parsedSource as Partial<LogResource>);
    }
}

export class NeuronItem {
    "id": string;
    "version": string;
    "state": number;

    /** Creates a new NeuronItem instance. */
    constructor($$source: Partial<NeuronItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NeuronItem instance from a string or object.
     */
    static createFrom($$source: any = {}): NeuronItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NeuronItem($$parsedSource as Partial<NeuronItem>);
    }
}

/**
 * NeuronVersionSummary is a built/retagged neuron version returned to the frontend.
 */
export class NeuronVersionSummary {
    "version": string;

    /**
     * unix seconds
     */
    "createTime": number;
    "buildCommit": string;
    "logsUrl": string;

    /** Creates a new NeuronVersionSummary instance. */
    constructor($$source: Partial<NeuronVersionSummary> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("buildCommit" in $$source)) {
            this["buildCommit"] = "";
        }
        if (!("logsUrl" in $$source)) {
            this["logsUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NeuronVersionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): NeuronVersionSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NeuronVersionSummary($$parsedSource as Partial<NeuronVersionSummary>);
    }
}

export class Organisation {
    "name": string;
    "displayName": string;
    "description": string;
    "logo": string;
    "account": string;

    /** Creates a new Organisation instance. */
    constructor($$source: Partial<Organisation> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("logo" in $$source)) {
            this["logo"] = "";
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Organisation instance from a string or object.
     */
    static createFrom($$source: any = {}): Organisation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Organisation($$parsedSource as Partial<Organisation>);
    }
}

/**
 * ScanNeuronPackages scans the neuron build directory for language config files.
 */
export class PackageInfo {
    "name": string;
    "language": string;
    "artifactId": string;

    /** Creates a new PackageInfo instance. */
    constructor($$source: Partial<PackageInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("artifactId" in $$source)) {
            this["artifactId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageInfo($$parsedSource as Partial<PackageInfo>);
    }
}

/**
 * PackageScript holds server-generated shell commands for one language folder.
 */
export class PackageScript {
    /**
     * display name: "asana-v1" or "asana-v1/proto"
     */
    "name": string;
    "title": string;
    "workDir": string;
    "lang": string;
    "install": string;
    "upgrade": string;
    "upgradeDefined": string;
    "add": string;

    /** Creates a new PackageScript instance. */
    constructor($$source: Partial<PackageScript> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("workDir" in $$source)) {
            this["workDir"] = "";
        }
        if (!("lang" in $$source)) {
            this["lang"] = "";
        }
        if (!("install" in $$source)) {
            this["install"] = "";
        }
        if (!("upgrade" in $$source)) {
            this["upgrade"] = "";
        }
        if (!("upgradeDefined" in $$source)) {
            this["upgradeDefined"] = "";
        }
        if (!("add" in $$source)) {
            this["add"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageScript instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageScript {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageScript($$parsedSource as Partial<PackageScript>);
    }
}

export class PkgRegistries {
    "go": string;
    "javascript": string;
    "python": string;

    /** Creates a new PkgRegistries instance. */
    constructor($$source: Partial<PkgRegistries> = {}) {
        if (!("go" in $$source)) {
            this["go"] = "";
        }
        if (!("javascript" in $$source)) {
            this["javascript"] = "";
        }
        if (!("python" in $$source)) {
            this["python"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PkgRegistries instance from a string or object.
     */
    static createFrom($$source: any = {}): PkgRegistries {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PkgRegistries($$parsedSource as Partial<PkgRegistries>);
    }
}

export class ProductOverview {
    "name": string;
    "displayName": string;
    "state": number;
    "googleProject"?: GCPProject | null;
    "gitRepo"?: GitRepoInfo | null;
    "packageRegistries"?: PkgRegistries | null;
    "dockerRegistry"?: string;

    /** Creates a new ProductOverview instance. */
    constructor($$source: Partial<ProductOverview> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProductOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): ProductOverview {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType21;
        const $$createField5_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("googleProject" in $$parsedSource) {
            $$parsedSource["googleProject"] = $$createField3_0($$parsedSource["googleProject"]);
        }
        if ("gitRepo" in $$parsedSource) {
            $$parsedSource["gitRepo"] = $$createField4_0($$parsedSource["gitRepo"]);
        }
        if ("packageRegistries" in $$parsedSource) {
            $$parsedSource["packageRegistries"] = $$createField5_0($$parsedSource["packageRegistries"]);
        }
        return new ProductOverview($$parsedSource as Partial<ProductOverview>);
    }
}

export class ProductSummary {
    "name": string;
    "displayName": string;
    "state": number;

    /** Creates a new ProductSummary instance. */
    constructor($$source: Partial<ProductSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProductSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProductSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProductSummary($$parsedSource as Partial<ProductSummary>);
    }
}

/**
 * RunBuildResult is returned to the frontend after initiating a Build.
 */
export class RunBuildResult {
    "operationName": string;
    "version": string;
    "neuronVersion": string;
    "logsUrl": string;
    "notes": string;
    "done": boolean;
    "error"?: string;

    /** Creates a new RunBuildResult instance. */
    constructor($$source: Partial<RunBuildResult> = {}) {
        if (!("operationName" in $$source)) {
            this["operationName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("neuronVersion" in $$source)) {
            this["neuronVersion"] = "";
        }
        if (!("logsUrl" in $$source)) {
            this["logsUrl"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunBuildResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RunBuildResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunBuildResult($$parsedSource as Partial<RunBuildResult>);
    }
}

/**
 * RunDefineResult is returned to the frontend after running a Define.
 */
export class RunDefineResult {
    "operationName": string;
    "definition": string;
    "version": string;
    "notes": string;
    "definitionArtifacts": string[];
    "done": boolean;
    "error"?: string;

    /** Creates a new RunDefineResult instance. */
    constructor($$source: Partial<RunDefineResult> = {}) {
        if (!("operationName" in $$source)) {
            this["operationName"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("definitionArtifacts" in $$source)) {
            this["definitionArtifacts"] = [];
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunDefineResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RunDefineResult {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definitionArtifacts" in $$parsedSource) {
            $$parsedSource["definitionArtifacts"] = $$createField4_0($$parsedSource["definitionArtifacts"]);
        }
        return new RunDefineResult($$parsedSource as Partial<RunDefineResult>);
    }
}

/**
 * RunDeployResult is returned to the frontend after initiating a Deploy.
 */
export class RunDeployResult {
    "operationName": string;
    "version": string;
    "deployments": (DeployItem | null)[];
    "notes": string;
    "done": boolean;
    "error"?: string;

    /** Creates a new RunDeployResult instance. */
    constructor($$source: Partial<RunDeployResult> = {}) {
        if (!("operationName" in $$source)) {
            this["operationName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("deployments" in $$source)) {
            this["deployments"] = [];
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunDeployResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RunDeployResult {
        const $$createField2_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deployments" in $$parsedSource) {
            $$parsedSource["deployments"] = $$createField2_0($$parsedSource["deployments"]);
        }
        return new RunDeployResult($$parsedSource as Partial<RunDeployResult>);
    }
}

export class SMSecret {
    "name": string;
    "createTime": string;
    "labels": { [_ in string]?: string };

    /** Creates a new SMSecret instance. */
    constructor($$source: Partial<SMSecret> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = "";
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SMSecret instance from a string or object.
     */
    static createFrom($$source: any = {}): SMSecret {
        const $$createField2_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        return new SMSecret($$parsedSource as Partial<SMSecret>);
    }
}

export class SMSecretVersion {
    "name": string;
    "createTime": string;
    "state": string;
    "destroyTime"?: string;

    /** Creates a new SMSecretVersion instance. */
    constructor($$source: Partial<SMSecretVersion> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SMSecretVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): SMSecretVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SMSecretVersion($$parsedSource as Partial<SMSecretVersion>);
    }
}

export class Service {
    "id": string;
    "name": string;
    "type": number;
    "state": number;
    "latestBuild": string;

    /** Creates a new Service instance. */
    constructor($$source: Partial<Service> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("latestBuild" in $$source)) {
            this["latestBuild"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     */
    static createFrom($$source: any = {}): Service {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service($$parsedSource as Partial<Service>);
    }
}

export class ServicesOverview {
    "neurons": NeuronItem[];
    "environments": EnvDeployments[];

    /** Creates a new ServicesOverview instance. */
    constructor($$source: Partial<ServicesOverview> = {}) {
        if (!("neurons" in $$source)) {
            this["neurons"] = [];
        }
        if (!("environments" in $$source)) {
            this["environments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServicesOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): ServicesOverview {
        const $$createField0_0 = $$createType28;
        const $$createField1_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("neurons" in $$parsedSource) {
            $$parsedSource["neurons"] = $$createField0_0($$parsedSource["neurons"]);
        }
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField1_0($$parsedSource["environments"]);
        }
        return new ServicesOverview($$parsedSource as Partial<ServicesOverview>);
    }
}

export class SetupChunk {
    "data": string;
    "done": boolean;
    "errMsg"?: string;

    /** Creates a new SetupChunk instance. */
    constructor($$source: Partial<SetupChunk> = {}) {
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SetupChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): SetupChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SetupChunk($$parsedSource as Partial<SetupChunk>);
    }
}

export class ShareAccount {
    "accountId": string;
    "displayName": string;
    "role": string;
    "isExternal": boolean;

    /** Creates a new ShareAccount instance. */
    constructor($$source: Partial<ShareAccount> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("isExternal" in $$source)) {
            this["isExternal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareAccount instance from a string or object.
     */
    static createFrom($$source: any = {}): ShareAccount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShareAccount($$parsedSource as Partial<ShareAccount>);
    }
}

export class ShareData {
    "people": SharePerson[];
    "accounts": ShareAccount[];
    "externalAccounts": ShareAccount[];

    /** Creates a new ShareData instance. */
    constructor($$source: Partial<ShareData> = {}) {
        if (!("people" in $$source)) {
            this["people"] = [];
        }
        if (!("accounts" in $$source)) {
            this["accounts"] = [];
        }
        if (!("externalAccounts" in $$source)) {
            this["externalAccounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareData instance from a string or object.
     */
    static createFrom($$source: any = {}): ShareData {
        const $$createField0_0 = $$createType32;
        const $$createField1_0 = $$createType34;
        const $$createField2_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField0_0($$parsedSource["people"]);
        }
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField1_0($$parsedSource["accounts"]);
        }
        if ("externalAccounts" in $$parsedSource) {
            $$parsedSource["externalAccounts"] = $$createField2_0($$parsedSource["externalAccounts"]);
        }
        return new ShareData($$parsedSource as Partial<ShareData>);
    }
}

export class SharePerson {
    "member": string;
    "displayName": string;
    "email": string;
    "photoUrl": string;
    "role": string;
    "isGroup": boolean;

    /** Creates a new SharePerson instance. */
    constructor($$source: Partial<SharePerson> = {}) {
        if (!("member" in $$source)) {
            this["member"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("photoUrl" in $$source)) {
            this["photoUrl"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("isGroup" in $$source)) {
            this["isGroup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharePerson instance from a string or object.
     */
    static createFrom($$source: any = {}): SharePerson {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SharePerson($$parsedSource as Partial<SharePerson>);
    }
}

export class SyncReposResult {
    "defineDir": string;
    "buildDir": string;
    "defineAction": string;
    "buildAction": string;
    "error"?: string;

    /** Creates a new SyncReposResult instance. */
    constructor($$source: Partial<SyncReposResult> = {}) {
        if (!("defineDir" in $$source)) {
            this["defineDir"] = "";
        }
        if (!("buildDir" in $$source)) {
            this["buildDir"] = "";
        }
        if (!("defineAction" in $$source)) {
            this["defineAction"] = "";
        }
        if (!("buildAction" in $$source)) {
            this["buildAction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncReposResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncReposResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncReposResult($$parsedSource as Partial<SyncReposResult>);
    }
}

export class UserProfile {
    "email": string;
    "name": string;
    "picture": string;

    /** Creates a new UserProfile instance. */
    constructor($$source: Partial<UserProfile> = {}) {
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("picture" in $$source)) {
            this["picture"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): UserProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserProfile($$parsedSource as Partial<UserProfile>);
    }
}

export class WorkspaceInfo {
    "organisation": string;
    "organisationDisplayName": string;
    "product": string;
    "productDisplayName": string;
    "environment": string;
    "environmentDisplayName": string;
    "environmentGoogleProjectId": string;
    "environmentGoogleRegion": string;
    "rootDirectory": string;

    /** Creates a new WorkspaceInfo instance. */
    constructor($$source: Partial<WorkspaceInfo> = {}) {
        if (!("organisation" in $$source)) {
            this["organisation"] = "";
        }
        if (!("organisationDisplayName" in $$source)) {
            this["organisationDisplayName"] = "";
        }
        if (!("product" in $$source)) {
            this["product"] = "";
        }
        if (!("productDisplayName" in $$source)) {
            this["productDisplayName"] = "";
        }
        if (!("environment" in $$source)) {
            this["environment"] = "";
        }
        if (!("environmentDisplayName" in $$source)) {
            this["environmentDisplayName"] = "";
        }
        if (!("environmentGoogleProjectId" in $$source)) {
            this["environmentGoogleProjectId"] = "";
        }
        if (!("environmentGoogleRegion" in $$source)) {
            this["environmentGoogleRegion"] = "";
        }
        if (!("rootDirectory" in $$source)) {
            this["rootDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceInfo($$parsedSource as Partial<WorkspaceInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DeploymentItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = GCPProject.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = GCSObject.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = GlassDefinition.createFrom;
const $$createType8 = GlassArtifact.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = InviteUserInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = Organisation.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = LogResource.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = LogEntry.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = GitRepoInfo.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = PkgRegistries.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = DeployItem.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = NeuronItem.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = EnvDeployments.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = SharePerson.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = ShareAccount.createFrom;
const $$createType34 = $Create.Array($$createType33);
