// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BuildLogsResult is returned by FetchBuildLogs.
 * NextOffset is the character count of all log text seen so far; pass it back on the
 * next call so only newly-appended lines are returned.
 */
export class BuildLogsResult {
    /**
     * Creates a new BuildLogsResult instance.
     * @param {Partial<BuildLogsResult>} [$$source = {}] - The source object to create the BuildLogsResult.
     */
    constructor($$source = {}) {
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("nextOffset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nextOffset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildLogsResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BuildLogsResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuildLogsResult(/** @type {Partial<BuildLogsResult>} */($$parsedSource));
    }
}

export class Codeblock {
    /**
     * Creates a new Codeblock instance.
     * @param {Partial<Codeblock>} [$$source = {}] - The source object to create the Codeblock.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("releaseLevel" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["releaseLevel"] = 0;
        }
        if (!("publisher" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publisher"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("headline" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["headline"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("bannerUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bannerUrl"] = "";
        }
        if (!("installCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["installCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Codeblock instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Codeblock}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Codeblock(/** @type {Partial<Codeblock>} */($$parsedSource));
    }
}

/**
 * DefineCommit represents a git commit in the define repository.
 */
export class DefineCommit {
    /**
     * Creates a new DefineCommit instance.
     * @param {Partial<DefineCommit>} [$$source = {}] - The source object to create the DefineCommit.
     */
    constructor($$source = {}) {
        if (!("sha" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["authorEmail"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DefineCommit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DefineCommit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DefineCommit(/** @type {Partial<DefineCommit>} */($$parsedSource));
    }
}

/**
 * DeployItem is a single deployment entry returned from the backend.
 */
export class DeployItem {
    /**
     * Creates a new DeployItem instance.
     * @param {Partial<DeployItem>} [$$source = {}] - The source object to create the DeployItem.
     */
    constructor($$source = {}) {
        if (!("logsUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logsUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeployItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeployItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeployItem(/** @type {Partial<DeployItem>} */($$parsedSource));
    }
}

export class DeploymentItem {
    /**
     * Creates a new DeploymentItem instance.
     * @param {Partial<DeploymentItem>} [$$source = {}] - The source object to create the DeploymentItem.
     */
    constructor($$source = {}) {
        if (!("neuronId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["neuronId"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["state"] = 0;
        }
        if (!("logsUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logsUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeploymentItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeploymentItem(/** @type {Partial<DeploymentItem>} */($$parsedSource));
    }
}

export class EnvDeployments {
    /**
     * Creates a new EnvDeployments instance.
     * @param {Partial<EnvDeployments>} [$$source = {}] - The source object to create the EnvDeployments.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("deployments" in $$source)) {
            /**
             * @member
             * @type {DeploymentItem[]}
             */
            this["deployments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvDeployments instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvDeployments}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deployments" in $$parsedSource) {
            $$parsedSource["deployments"] = $$createField2_0($$parsedSource["deployments"]);
        }
        return new EnvDeployments(/** @type {Partial<EnvDeployments>} */($$parsedSource));
    }
}

export class EnvInfo {
    /**
     * Creates a new EnvInfo instance.
     * @param {Partial<EnvInfo>} [$$source = {}] - The source object to create the EnvInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["state"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GCPProject | null | undefined}
             */
            this["gcpProject"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("gcpProject" in $$parsedSource) {
            $$parsedSource["gcpProject"] = $$createField3_0($$parsedSource["gcpProject"]);
        }
        return new EnvInfo(/** @type {Partial<EnvInfo>} */($$parsedSource));
    }
}

export class EnvVariable {
    /**
     * Creates a new EnvVariable instance.
     * @param {Partial<EnvVariable>} [$$source = {}] - The source object to create the EnvVariable.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvVariable instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EnvVariable}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvVariable(/** @type {Partial<EnvVariable>} */($$parsedSource));
    }
}

export class GCPProject {
    /**
     * Creates a new GCPProject instance.
     * @param {Partial<GCPProject>} [$$source = {}] - The source object to create the GCPProject.
     */
    constructor($$source = {}) {
        if (!("folderId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("number" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["number"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (!("billingAccountId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["billingAccountId"] = "";
        }
        if (!("managedBillingAccount" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["managedBillingAccount"] = false;
        }
        if (!("cloudUri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cloudUri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GCPProject instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GCPProject}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GCPProject(/** @type {Partial<GCPProject>} */($$parsedSource));
    }
}

export class GitRepoInfo {
    /**
     * Creates a new GitRepoInfo instance.
     * @param {Partial<GitRepoInfo>} [$$source = {}] - The source object to create the GitRepoInfo.
     */
    constructor($$source = {}) {
        if (!("remoteUri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteUri"] = "";
        }
        if (!("cloudRunUri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cloudRunUri"] = "";
        }
        if (!("vmUri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["vmUri"] = "";
        }
        if (!("bucketUri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bucketUri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitRepoInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitRepoInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitRepoInfo(/** @type {Partial<GitRepoInfo>} */($$parsedSource));
    }
}

/**
 * GlassArtifact is one artifact type from ExplainDefine.
 */
export class GlassArtifact {
    /**
     * Creates a new GlassArtifact instance.
     * @param {Partial<GlassArtifact>} [$$source = {}] - The source object to create the GlassArtifact.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["state"] = 0;
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("locationUri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["locationUri"] = "";
        }
        if (!("extra" in $$source)) {
            /**
             * packageImportPath (Go) or packageName (JS)
             * @member
             * @type {string}
             */
            this["extra"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassArtifact instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlassArtifact}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlassArtifact(/** @type {Partial<GlassArtifact>} */($$parsedSource));
    }
}

/**
 * GlassDefinition holds current definition metadata from ExplainDefine.
 */
export class GlassDefinition {
    /**
     * Creates a new GlassDefinition instance.
     * @param {Partial<GlassDefinition>} [$$source = {}] - The source object to create the GlassDefinition.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commit"] = "";
        }
        if (!("releaseType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlassDefinition}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlassDefinition(/** @type {Partial<GlassDefinition>} */($$parsedSource));
    }
}

/**
 * GlassResult is the response from ExplainDefine.
 */
export class GlassResult {
    /**
     * Creates a new GlassResult instance.
     * @param {Partial<GlassResult>} [$$source = {}] - The source object to create the GlassResult.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("definition" in $$source)) {
            /**
             * @member
             * @type {GlassDefinition}
             */
            this["definition"] = (new GlassDefinition());
        }
        if (!("artifacts" in $$source)) {
            /**
             * @member
             * @type {GlassArtifact[]}
             */
            this["artifacts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlassResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definition" in $$parsedSource) {
            $$parsedSource["definition"] = $$createField2_0($$parsedSource["definition"]);
        }
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField3_0($$parsedSource["artifacts"]);
        }
        return new GlassResult(/** @type {Partial<GlassResult>} */($$parsedSource));
    }
}

export class InviteInfo {
    /**
     * Creates a new InviteInfo instance.
     * @param {Partial<InviteInfo>} [$$source = {}] - The source object to create the InviteInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("buildSeat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["buildSeat"] = 0;
        }
        if (!("manageSeat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["manageSeat"] = 0;
        }
        if (!("allowAll" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allowAll"] = false;
        }
        if (!("domains" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["domains"] = [];
        }
        if (!("users" in $$source)) {
            /**
             * @member
             * @type {InviteUserInfo[]}
             */
            this["users"] = [];
        }
        if (!("inviter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["inviter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InviteInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InviteInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("domains" in $$parsedSource) {
            $$parsedSource["domains"] = $$createField4_0($$parsedSource["domains"]);
        }
        if ("users" in $$parsedSource) {
            $$parsedSource["users"] = $$createField5_0($$parsedSource["users"]);
        }
        return new InviteInfo(/** @type {Partial<InviteInfo>} */($$parsedSource));
    }
}

export class InviteUserInfo {
    /**
     * Creates a new InviteUserInfo instance.
     * @param {Partial<InviteUserInfo>} [$$source = {}] - The source object to create the InviteUserInfo.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("profilePicture" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profilePicture"] = "";
        }
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("claimed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["claimed"] = false;
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["role"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InviteUserInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InviteUserInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InviteUserInfo(/** @type {Partial<InviteUserInfo>} */($$parsedSource));
    }
}

export class LandingZonesData {
    /**
     * Creates a new LandingZonesData instance.
     * @param {Partial<LandingZonesData>} [$$source = {}] - The source object to create the LandingZonesData.
     */
    constructor($$source = {}) {
        if (!("own" in $$source)) {
            /**
             * @member
             * @type {Organisation[]}
             */
            this["own"] = [];
        }
        if (!("shared" in $$source)) {
            /**
             * @member
             * @type {Organisation[]}
             */
            this["shared"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LandingZonesData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LandingZonesData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("own" in $$parsedSource) {
            $$parsedSource["own"] = $$createField0_0($$parsedSource["own"]);
        }
        if ("shared" in $$parsedSource) {
            $$parsedSource["shared"] = $$createField1_0($$parsedSource["shared"]);
        }
        return new LandingZonesData(/** @type {Partial<LandingZonesData>} */($$parsedSource));
    }
}

/**
 * LocalBuildChunk is a polling response for a running local Docker build.
 */
export class LocalBuildChunk {
    /**
     * Creates a new LocalBuildChunk instance.
     * @param {Partial<LocalBuildChunk>} [$$source = {}] - The source object to create the LocalBuildChunk.
     */
    constructor($$source = {}) {
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("nextOffset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nextOffset"] = 0;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalBuildChunk instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalBuildChunk}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalBuildChunk(/** @type {Partial<LocalBuildChunk>} */($$parsedSource));
    }
}

/**
 * LocalBuildResult is returned when a local Docker build is started.
 */
export class LocalBuildResult {
    /**
     * Creates a new LocalBuildResult instance.
     * @param {Partial<LocalBuildResult>} [$$source = {}] - The source object to create the LocalBuildResult.
     */
    constructor($$source = {}) {
        if (!("buildId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalBuildResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalBuildResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalBuildResult(/** @type {Partial<LocalBuildResult>} */($$parsedSource));
    }
}

export class NeuronItem {
    /**
     * Creates a new NeuronItem instance.
     * @param {Partial<NeuronItem>} [$$source = {}] - The source object to create the NeuronItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NeuronItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NeuronItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NeuronItem(/** @type {Partial<NeuronItem>} */($$parsedSource));
    }
}

/**
 * NeuronVersionSummary is a built/retagged neuron version returned to the frontend.
 */
export class NeuronVersionSummary {
    /**
     * Creates a new NeuronVersionSummary instance.
     * @param {Partial<NeuronVersionSummary>} [$$source = {}] - The source object to create the NeuronVersionSummary.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("createTime" in $$source)) {
            /**
             * unix seconds
             * @member
             * @type {number}
             */
            this["createTime"] = 0;
        }
        if (!("buildCommit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildCommit"] = "";
        }
        if (!("logsUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logsUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NeuronVersionSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NeuronVersionSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NeuronVersionSummary(/** @type {Partial<NeuronVersionSummary>} */($$parsedSource));
    }
}

export class Organisation {
    /**
     * Creates a new Organisation instance.
     * @param {Partial<Organisation>} [$$source = {}] - The source object to create the Organisation.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("logo" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logo"] = "";
        }
        if (!("account" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["account"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Organisation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Organisation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Organisation(/** @type {Partial<Organisation>} */($$parsedSource));
    }
}

/**
 * ScanNeuronPackages scans the neuron build directory for language config files.
 */
export class PackageInfo {
    /**
     * Creates a new PackageInfo instance.
     * @param {Partial<PackageInfo>} [$$source = {}] - The source object to create the PackageInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("artifactId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackageInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageInfo(/** @type {Partial<PackageInfo>} */($$parsedSource));
    }
}

/**
 * PackageScript holds server-generated shell commands for one language folder.
 */
export class PackageScript {
    /**
     * Creates a new PackageScript instance.
     * @param {Partial<PackageScript>} [$$source = {}] - The source object to create the PackageScript.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * display name: "asana-v1" or "asana-v1/proto"
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("workDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workDir"] = "";
        }
        if (!("lang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lang"] = "";
        }
        if (!("install" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["install"] = "";
        }
        if (!("upgrade" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["upgrade"] = "";
        }
        if (!("upgradeDefined" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["upgradeDefined"] = "";
        }
        if (!("add" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["add"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageScript instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PackageScript}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageScript(/** @type {Partial<PackageScript>} */($$parsedSource));
    }
}

export class PkgRegistries {
    /**
     * Creates a new PkgRegistries instance.
     * @param {Partial<PkgRegistries>} [$$source = {}] - The source object to create the PkgRegistries.
     */
    constructor($$source = {}) {
        if (!("go" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["go"] = "";
        }
        if (!("javascript" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["javascript"] = "";
        }
        if (!("python" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["python"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PkgRegistries instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PkgRegistries}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PkgRegistries(/** @type {Partial<PkgRegistries>} */($$parsedSource));
    }
}

export class ProductOverview {
    /**
     * Creates a new ProductOverview instance.
     * @param {Partial<ProductOverview>} [$$source = {}] - The source object to create the ProductOverview.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["state"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GCPProject | null | undefined}
             */
            this["googleProject"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GitRepoInfo | null | undefined}
             */
            this["gitRepo"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PkgRegistries | null | undefined}
             */
            this["packageRegistries"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dockerRegistry"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProductOverview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProductOverview}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType13;
        const $$createField5_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("googleProject" in $$parsedSource) {
            $$parsedSource["googleProject"] = $$createField3_0($$parsedSource["googleProject"]);
        }
        if ("gitRepo" in $$parsedSource) {
            $$parsedSource["gitRepo"] = $$createField4_0($$parsedSource["gitRepo"]);
        }
        if ("packageRegistries" in $$parsedSource) {
            $$parsedSource["packageRegistries"] = $$createField5_0($$parsedSource["packageRegistries"]);
        }
        return new ProductOverview(/** @type {Partial<ProductOverview>} */($$parsedSource));
    }
}

export class ProductSummary {
    /**
     * Creates a new ProductSummary instance.
     * @param {Partial<ProductSummary>} [$$source = {}] - The source object to create the ProductSummary.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProductSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProductSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProductSummary(/** @type {Partial<ProductSummary>} */($$parsedSource));
    }
}

/**
 * RunBuildResult is returned to the frontend after initiating a Build.
 */
export class RunBuildResult {
    /**
     * Creates a new RunBuildResult instance.
     * @param {Partial<RunBuildResult>} [$$source = {}] - The source object to create the RunBuildResult.
     */
    constructor($$source = {}) {
        if (!("operationName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operationName"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("neuronVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["neuronVersion"] = "";
        }
        if (!("logsUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logsUrl"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunBuildResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunBuildResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunBuildResult(/** @type {Partial<RunBuildResult>} */($$parsedSource));
    }
}

/**
 * RunDefineResult is returned to the frontend after running a Define.
 */
export class RunDefineResult {
    /**
     * Creates a new RunDefineResult instance.
     * @param {Partial<RunDefineResult>} [$$source = {}] - The source object to create the RunDefineResult.
     */
    constructor($$source = {}) {
        if (!("operationName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operationName"] = "";
        }
        if (!("definition" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["definition"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("definitionArtifacts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["definitionArtifacts"] = [];
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunDefineResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunDefineResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definitionArtifacts" in $$parsedSource) {
            $$parsedSource["definitionArtifacts"] = $$createField4_0($$parsedSource["definitionArtifacts"]);
        }
        return new RunDefineResult(/** @type {Partial<RunDefineResult>} */($$parsedSource));
    }
}

/**
 * RunDeployResult is returned to the frontend after initiating a Deploy.
 */
export class RunDeployResult {
    /**
     * Creates a new RunDeployResult instance.
     * @param {Partial<RunDeployResult>} [$$source = {}] - The source object to create the RunDeployResult.
     */
    constructor($$source = {}) {
        if (!("operationName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operationName"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("deployments" in $$source)) {
            /**
             * @member
             * @type {(DeployItem | null)[]}
             */
            this["deployments"] = [];
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunDeployResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunDeployResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deployments" in $$parsedSource) {
            $$parsedSource["deployments"] = $$createField2_0($$parsedSource["deployments"]);
        }
        return new RunDeployResult(/** @type {Partial<RunDeployResult>} */($$parsedSource));
    }
}

export class Service {
    /**
     * Creates a new Service instance.
     * @param {Partial<Service>} [$$source = {}] - The source object to create the Service.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["type"] = 0;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["state"] = 0;
        }
        if (!("latestBuild" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestBuild"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Service}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service(/** @type {Partial<Service>} */($$parsedSource));
    }
}

export class ServicesOverview {
    /**
     * Creates a new ServicesOverview instance.
     * @param {Partial<ServicesOverview>} [$$source = {}] - The source object to create the ServicesOverview.
     */
    constructor($$source = {}) {
        if (!("neurons" in $$source)) {
            /**
             * @member
             * @type {NeuronItem[]}
             */
            this["neurons"] = [];
        }
        if (!("environments" in $$source)) {
            /**
             * @member
             * @type {EnvDeployments[]}
             */
            this["environments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServicesOverview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServicesOverview}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType20;
        const $$createField1_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("neurons" in $$parsedSource) {
            $$parsedSource["neurons"] = $$createField0_0($$parsedSource["neurons"]);
        }
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField1_0($$parsedSource["environments"]);
        }
        return new ServicesOverview(/** @type {Partial<ServicesOverview>} */($$parsedSource));
    }
}

export class ShareAccount {
    /**
     * Creates a new ShareAccount instance.
     * @param {Partial<ShareAccount>} [$$source = {}] - The source object to create the ShareAccount.
     */
    constructor($$source = {}) {
        if (!("accountId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accountId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("isExternal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isExternal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareAccount instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShareAccount}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShareAccount(/** @type {Partial<ShareAccount>} */($$parsedSource));
    }
}

export class ShareData {
    /**
     * Creates a new ShareData instance.
     * @param {Partial<ShareData>} [$$source = {}] - The source object to create the ShareData.
     */
    constructor($$source = {}) {
        if (!("people" in $$source)) {
            /**
             * @member
             * @type {SharePerson[]}
             */
            this["people"] = [];
        }
        if (!("accounts" in $$source)) {
            /**
             * @member
             * @type {ShareAccount[]}
             */
            this["accounts"] = [];
        }
        if (!("externalAccounts" in $$source)) {
            /**
             * @member
             * @type {ShareAccount[]}
             */
            this["externalAccounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShareData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType26;
        const $$createField2_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField0_0($$parsedSource["people"]);
        }
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField1_0($$parsedSource["accounts"]);
        }
        if ("externalAccounts" in $$parsedSource) {
            $$parsedSource["externalAccounts"] = $$createField2_0($$parsedSource["externalAccounts"]);
        }
        return new ShareData(/** @type {Partial<ShareData>} */($$parsedSource));
    }
}

export class SharePerson {
    /**
     * Creates a new SharePerson instance.
     * @param {Partial<SharePerson>} [$$source = {}] - The source object to create the SharePerson.
     */
    constructor($$source = {}) {
        if (!("member" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["member"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("photoUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["photoUrl"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("isGroup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isGroup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharePerson instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SharePerson}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SharePerson(/** @type {Partial<SharePerson>} */($$parsedSource));
    }
}

export class SyncReposResult {
    /**
     * Creates a new SyncReposResult instance.
     * @param {Partial<SyncReposResult>} [$$source = {}] - The source object to create the SyncReposResult.
     */
    constructor($$source = {}) {
        if (!("defineDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defineDir"] = "";
        }
        if (!("buildDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildDir"] = "";
        }
        if (!("defineAction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defineAction"] = "";
        }
        if (!("buildAction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildAction"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncReposResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SyncReposResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncReposResult(/** @type {Partial<SyncReposResult>} */($$parsedSource));
    }
}

export class UserProfile {
    /**
     * Creates a new UserProfile instance.
     * @param {Partial<UserProfile>} [$$source = {}] - The source object to create the UserProfile.
     */
    constructor($$source = {}) {
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("picture" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["picture"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserProfile(/** @type {Partial<UserProfile>} */($$parsedSource));
    }
}

export class WorkspaceInfo {
    /**
     * Creates a new WorkspaceInfo instance.
     * @param {Partial<WorkspaceInfo>} [$$source = {}] - The source object to create the WorkspaceInfo.
     */
    constructor($$source = {}) {
        if (!("organisation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["organisation"] = "";
        }
        if (!("organisationDisplayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["organisationDisplayName"] = "";
        }
        if (!("product" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["product"] = "";
        }
        if (!("productDisplayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["productDisplayName"] = "";
        }
        if (!("environment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["environment"] = "";
        }
        if (!("environmentDisplayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["environmentDisplayName"] = "";
        }
        if (!("environmentGoogleProjectId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["environmentGoogleProjectId"] = "";
        }
        if (!("environmentGoogleRegion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["environmentGoogleRegion"] = "";
        }
        if (!("rootDirectory" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rootDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceInfo(/** @type {Partial<WorkspaceInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DeploymentItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = GCPProject.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = GlassDefinition.createFrom;
const $$createType5 = GlassArtifact.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = InviteUserInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Organisation.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = GitRepoInfo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = PkgRegistries.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = DeployItem.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = NeuronItem.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = EnvDeployments.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = SharePerson.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = ShareAccount.createFrom;
const $$createType26 = $Create.Array($$createType25);
