// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DefineCommit represents a git commit in the define repository.
 */
export class DefineCommit {
    "sha": string;
    "message": string;
    "author": string;
    "authorEmail": string;
    "timestamp": number;

    /** Creates a new DefineCommit instance. */
    constructor($$source: Partial<DefineCommit> = {}) {
        if (!("sha" in $$source)) {
            this["sha"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("authorEmail" in $$source)) {
            this["authorEmail"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DefineCommit instance from a string or object.
     */
    static createFrom($$source: any = {}): DefineCommit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DefineCommit($$parsedSource as Partial<DefineCommit>);
    }
}

export class DeploymentItem {
    "neuronId": string;
    "version": string;
    "state": number;
    "logsUrl": string;

    /** Creates a new DeploymentItem instance. */
    constructor($$source: Partial<DeploymentItem> = {}) {
        if (!("neuronId" in $$source)) {
            this["neuronId"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("logsUrl" in $$source)) {
            this["logsUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeploymentItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DeploymentItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeploymentItem($$parsedSource as Partial<DeploymentItem>);
    }
}

export class EnvDeployments {
    "name": string;
    "displayName": string;
    "deployments": DeploymentItem[];

    /** Creates a new EnvDeployments instance. */
    constructor($$source: Partial<EnvDeployments> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("deployments" in $$source)) {
            this["deployments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvDeployments instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvDeployments {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("deployments" in $$parsedSource) {
            $$parsedSource["deployments"] = $$createField2_0($$parsedSource["deployments"]);
        }
        return new EnvDeployments($$parsedSource as Partial<EnvDeployments>);
    }
}

export class EnvInfo {
    "name": string;
    "displayName": string;
    "state": number;
    "gcpProject"?: GCPProject | null;

    /** Creates a new EnvInfo instance. */
    constructor($$source: Partial<EnvInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvInfo {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("gcpProject" in $$parsedSource) {
            $$parsedSource["gcpProject"] = $$createField3_0($$parsedSource["gcpProject"]);
        }
        return new EnvInfo($$parsedSource as Partial<EnvInfo>);
    }
}

export class GCPProject {
    "folderId": string;
    "id": string;
    "number": string;
    "region": string;
    "billingAccountId": string;
    "managedBillingAccount": boolean;
    "cloudUri": string;

    /** Creates a new GCPProject instance. */
    constructor($$source: Partial<GCPProject> = {}) {
        if (!("folderId" in $$source)) {
            this["folderId"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("billingAccountId" in $$source)) {
            this["billingAccountId"] = "";
        }
        if (!("managedBillingAccount" in $$source)) {
            this["managedBillingAccount"] = false;
        }
        if (!("cloudUri" in $$source)) {
            this["cloudUri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GCPProject instance from a string or object.
     */
    static createFrom($$source: any = {}): GCPProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GCPProject($$parsedSource as Partial<GCPProject>);
    }
}

export class GitRepoInfo {
    "remoteUri": string;
    "cloudRunUri": string;
    "vmUri": string;
    "bucketUri": string;

    /** Creates a new GitRepoInfo instance. */
    constructor($$source: Partial<GitRepoInfo> = {}) {
        if (!("remoteUri" in $$source)) {
            this["remoteUri"] = "";
        }
        if (!("cloudRunUri" in $$source)) {
            this["cloudRunUri"] = "";
        }
        if (!("vmUri" in $$source)) {
            this["vmUri"] = "";
        }
        if (!("bucketUri" in $$source)) {
            this["bucketUri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitRepoInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): GitRepoInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitRepoInfo($$parsedSource as Partial<GitRepoInfo>);
    }
}

/**
 * GlassArtifact is one artifact type from ExplainDefine.
 */
export class GlassArtifact {
    "type": string;
    "state": number;
    "notes": string;
    "locationUri": string;

    /**
     * packageImportPath (Go) or packageName (JS)
     */
    "extra": string;

    /** Creates a new GlassArtifact instance. */
    constructor($$source: Partial<GlassArtifact> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("locationUri" in $$source)) {
            this["locationUri"] = "";
        }
        if (!("extra" in $$source)) {
            this["extra"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassArtifact instance from a string or object.
     */
    static createFrom($$source: any = {}): GlassArtifact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlassArtifact($$parsedSource as Partial<GlassArtifact>);
    }
}

/**
 * GlassDefinition holds current definition metadata from ExplainDefine.
 */
export class GlassDefinition {
    "name": string;
    "version": string;
    "commit": string;
    "releaseType": string;

    /** Creates a new GlassDefinition instance. */
    constructor($$source: Partial<GlassDefinition> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("commit" in $$source)) {
            this["commit"] = "";
        }
        if (!("releaseType" in $$source)) {
            this["releaseType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): GlassDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlassDefinition($$parsedSource as Partial<GlassDefinition>);
    }
}

/**
 * GlassResult is the response from ExplainDefine.
 */
export class GlassResult {
    "title": string;
    "summary": string;
    "definition": GlassDefinition;
    "artifacts": GlassArtifact[];

    /** Creates a new GlassResult instance. */
    constructor($$source: Partial<GlassResult> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = (new GlassDefinition());
        }
        if (!("artifacts" in $$source)) {
            this["artifacts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlassResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GlassResult {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definition" in $$parsedSource) {
            $$parsedSource["definition"] = $$createField2_0($$parsedSource["definition"]);
        }
        if ("artifacts" in $$parsedSource) {
            $$parsedSource["artifacts"] = $$createField3_0($$parsedSource["artifacts"]);
        }
        return new GlassResult($$parsedSource as Partial<GlassResult>);
    }
}

export class InviteInfo {
    "name": string;
    "buildSeat": number;
    "manageSeat": number;
    "allowAll": boolean;
    "domains": string[];
    "users": InviteUserInfo[];
    "inviter": string;

    /** Creates a new InviteInfo instance. */
    constructor($$source: Partial<InviteInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("buildSeat" in $$source)) {
            this["buildSeat"] = 0;
        }
        if (!("manageSeat" in $$source)) {
            this["manageSeat"] = 0;
        }
        if (!("allowAll" in $$source)) {
            this["allowAll"] = false;
        }
        if (!("domains" in $$source)) {
            this["domains"] = [];
        }
        if (!("users" in $$source)) {
            this["users"] = [];
        }
        if (!("inviter" in $$source)) {
            this["inviter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InviteInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): InviteInfo {
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("domains" in $$parsedSource) {
            $$parsedSource["domains"] = $$createField4_0($$parsedSource["domains"]);
        }
        if ("users" in $$parsedSource) {
            $$parsedSource["users"] = $$createField5_0($$parsedSource["users"]);
        }
        return new InviteInfo($$parsedSource as Partial<InviteInfo>);
    }
}

export class InviteUserInfo {
    "user": string;
    "email": string;
    "displayName": string;
    "profilePicture": string;
    "domain": string;
    "claimed": boolean;
    "role": number;

    /** Creates a new InviteUserInfo instance. */
    constructor($$source: Partial<InviteUserInfo> = {}) {
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("profilePicture" in $$source)) {
            this["profilePicture"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("claimed" in $$source)) {
            this["claimed"] = false;
        }
        if (!("role" in $$source)) {
            this["role"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InviteUserInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): InviteUserInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InviteUserInfo($$parsedSource as Partial<InviteUserInfo>);
    }
}

export class LandingZonesData {
    "own": Organisation[];
    "shared": Organisation[];

    /** Creates a new LandingZonesData instance. */
    constructor($$source: Partial<LandingZonesData> = {}) {
        if (!("own" in $$source)) {
            this["own"] = [];
        }
        if (!("shared" in $$source)) {
            this["shared"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LandingZonesData instance from a string or object.
     */
    static createFrom($$source: any = {}): LandingZonesData {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("own" in $$parsedSource) {
            $$parsedSource["own"] = $$createField0_0($$parsedSource["own"]);
        }
        if ("shared" in $$parsedSource) {
            $$parsedSource["shared"] = $$createField1_0($$parsedSource["shared"]);
        }
        return new LandingZonesData($$parsedSource as Partial<LandingZonesData>);
    }
}

export class NeuronItem {
    "id": string;
    "version": string;
    "state": number;

    /** Creates a new NeuronItem instance. */
    constructor($$source: Partial<NeuronItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NeuronItem instance from a string or object.
     */
    static createFrom($$source: any = {}): NeuronItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NeuronItem($$parsedSource as Partial<NeuronItem>);
    }
}

export class Organisation {
    "name": string;
    "displayName": string;
    "description": string;
    "logo": string;
    "account": string;

    /** Creates a new Organisation instance. */
    constructor($$source: Partial<Organisation> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("logo" in $$source)) {
            this["logo"] = "";
        }
        if (!("account" in $$source)) {
            this["account"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Organisation instance from a string or object.
     */
    static createFrom($$source: any = {}): Organisation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Organisation($$parsedSource as Partial<Organisation>);
    }
}

/**
 * ScanNeuronPackages scans the neuron build directory for language config files.
 */
export class PackageInfo {
    "name": string;
    "language": string;
    "artifactId": string;

    /** Creates a new PackageInfo instance. */
    constructor($$source: Partial<PackageInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("artifactId" in $$source)) {
            this["artifactId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PackageInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PackageInfo($$parsedSource as Partial<PackageInfo>);
    }
}

export class PkgRegistries {
    "go": string;
    "javascript": string;
    "python": string;

    /** Creates a new PkgRegistries instance. */
    constructor($$source: Partial<PkgRegistries> = {}) {
        if (!("go" in $$source)) {
            this["go"] = "";
        }
        if (!("javascript" in $$source)) {
            this["javascript"] = "";
        }
        if (!("python" in $$source)) {
            this["python"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PkgRegistries instance from a string or object.
     */
    static createFrom($$source: any = {}): PkgRegistries {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PkgRegistries($$parsedSource as Partial<PkgRegistries>);
    }
}

export class ProductOverview {
    "name": string;
    "displayName": string;
    "state": number;
    "googleProject"?: GCPProject | null;
    "gitRepo"?: GitRepoInfo | null;
    "packageRegistries"?: PkgRegistries | null;
    "dockerRegistry"?: string;

    /** Creates a new ProductOverview instance. */
    constructor($$source: Partial<ProductOverview> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProductOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): ProductOverview {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType13;
        const $$createField5_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("googleProject" in $$parsedSource) {
            $$parsedSource["googleProject"] = $$createField3_0($$parsedSource["googleProject"]);
        }
        if ("gitRepo" in $$parsedSource) {
            $$parsedSource["gitRepo"] = $$createField4_0($$parsedSource["gitRepo"]);
        }
        if ("packageRegistries" in $$parsedSource) {
            $$parsedSource["packageRegistries"] = $$createField5_0($$parsedSource["packageRegistries"]);
        }
        return new ProductOverview($$parsedSource as Partial<ProductOverview>);
    }
}

export class ProductSummary {
    "name": string;
    "displayName": string;
    "state": number;

    /** Creates a new ProductSummary instance. */
    constructor($$source: Partial<ProductSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProductSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProductSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProductSummary($$parsedSource as Partial<ProductSummary>);
    }
}

/**
 * RunBuildResult is returned to the frontend after initiating a Build.
 */
export class RunBuildResult {
    "operationName": string;
    "version": string;
    "neuronVersion": string;
    "logsUrl": string;
    "notes": string;
    "done": boolean;
    "error"?: string;

    /** Creates a new RunBuildResult instance. */
    constructor($$source: Partial<RunBuildResult> = {}) {
        if (!("operationName" in $$source)) {
            this["operationName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("neuronVersion" in $$source)) {
            this["neuronVersion"] = "";
        }
        if (!("logsUrl" in $$source)) {
            this["logsUrl"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunBuildResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RunBuildResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunBuildResult($$parsedSource as Partial<RunBuildResult>);
    }
}

/**
 * RunDefineResult is returned to the frontend after running a Define.
 */
export class RunDefineResult {
    "operationName": string;
    "definition": string;
    "version": string;
    "notes": string;
    "definitionArtifacts": string[];
    "done": boolean;
    "error"?: string;

    /** Creates a new RunDefineResult instance. */
    constructor($$source: Partial<RunDefineResult> = {}) {
        if (!("operationName" in $$source)) {
            this["operationName"] = "";
        }
        if (!("definition" in $$source)) {
            this["definition"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("definitionArtifacts" in $$source)) {
            this["definitionArtifacts"] = [];
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunDefineResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RunDefineResult {
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definitionArtifacts" in $$parsedSource) {
            $$parsedSource["definitionArtifacts"] = $$createField4_0($$parsedSource["definitionArtifacts"]);
        }
        return new RunDefineResult($$parsedSource as Partial<RunDefineResult>);
    }
}

export class Service {
    "id": string;
    "name": string;
    "type": number;
    "state": number;
    "latestBuild": string;

    /** Creates a new Service instance. */
    constructor($$source: Partial<Service> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("latestBuild" in $$source)) {
            this["latestBuild"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Service instance from a string or object.
     */
    static createFrom($$source: any = {}): Service {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Service($$parsedSource as Partial<Service>);
    }
}

export class ServicesOverview {
    "neurons": NeuronItem[];
    "environments": EnvDeployments[];

    /** Creates a new ServicesOverview instance. */
    constructor($$source: Partial<ServicesOverview> = {}) {
        if (!("neurons" in $$source)) {
            this["neurons"] = [];
        }
        if (!("environments" in $$source)) {
            this["environments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServicesOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): ServicesOverview {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("neurons" in $$parsedSource) {
            $$parsedSource["neurons"] = $$createField0_0($$parsedSource["neurons"]);
        }
        if ("environments" in $$parsedSource) {
            $$parsedSource["environments"] = $$createField1_0($$parsedSource["environments"]);
        }
        return new ServicesOverview($$parsedSource as Partial<ServicesOverview>);
    }
}

export class ShareAccount {
    "accountId": string;
    "displayName": string;
    "role": string;
    "isExternal": boolean;

    /** Creates a new ShareAccount instance. */
    constructor($$source: Partial<ShareAccount> = {}) {
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("isExternal" in $$source)) {
            this["isExternal"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareAccount instance from a string or object.
     */
    static createFrom($$source: any = {}): ShareAccount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShareAccount($$parsedSource as Partial<ShareAccount>);
    }
}

export class ShareData {
    "people": SharePerson[];
    "accounts": ShareAccount[];
    "externalAccounts": ShareAccount[];

    /** Creates a new ShareData instance. */
    constructor($$source: Partial<ShareData> = {}) {
        if (!("people" in $$source)) {
            this["people"] = [];
        }
        if (!("accounts" in $$source)) {
            this["accounts"] = [];
        }
        if (!("externalAccounts" in $$source)) {
            this["externalAccounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareData instance from a string or object.
     */
    static createFrom($$source: any = {}): ShareData {
        const $$createField0_0 = $$createType21;
        const $$createField1_0 = $$createType23;
        const $$createField2_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("people" in $$parsedSource) {
            $$parsedSource["people"] = $$createField0_0($$parsedSource["people"]);
        }
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField1_0($$parsedSource["accounts"]);
        }
        if ("externalAccounts" in $$parsedSource) {
            $$parsedSource["externalAccounts"] = $$createField2_0($$parsedSource["externalAccounts"]);
        }
        return new ShareData($$parsedSource as Partial<ShareData>);
    }
}

export class SharePerson {
    "member": string;
    "displayName": string;
    "email": string;
    "photoUrl": string;
    "role": string;
    "isGroup": boolean;

    /** Creates a new SharePerson instance. */
    constructor($$source: Partial<SharePerson> = {}) {
        if (!("member" in $$source)) {
            this["member"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("email" in $$source)) {
            this["email"] = "";
        }
        if (!("photoUrl" in $$source)) {
            this["photoUrl"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("isGroup" in $$source)) {
            this["isGroup"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharePerson instance from a string or object.
     */
    static createFrom($$source: any = {}): SharePerson {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SharePerson($$parsedSource as Partial<SharePerson>);
    }
}

export class WorkspaceInfo {
    "organisation": string;
    "organisationDisplayName": string;
    "product": string;
    "productDisplayName": string;
    "environment": string;
    "environmentDisplayName": string;
    "environmentGoogleProjectId": string;
    "environmentGoogleRegion": string;
    "rootDirectory": string;

    /** Creates a new WorkspaceInfo instance. */
    constructor($$source: Partial<WorkspaceInfo> = {}) {
        if (!("organisation" in $$source)) {
            this["organisation"] = "";
        }
        if (!("organisationDisplayName" in $$source)) {
            this["organisationDisplayName"] = "";
        }
        if (!("product" in $$source)) {
            this["product"] = "";
        }
        if (!("productDisplayName" in $$source)) {
            this["productDisplayName"] = "";
        }
        if (!("environment" in $$source)) {
            this["environment"] = "";
        }
        if (!("environmentDisplayName" in $$source)) {
            this["environmentDisplayName"] = "";
        }
        if (!("environmentGoogleProjectId" in $$source)) {
            this["environmentGoogleProjectId"] = "";
        }
        if (!("environmentGoogleRegion" in $$source)) {
            this["environmentGoogleRegion"] = "";
        }
        if (!("rootDirectory" in $$source)) {
            this["rootDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceInfo($$parsedSource as Partial<WorkspaceInfo>);
    }
}

// Private type creation functions
const $$createType0 = DeploymentItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = GCPProject.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = GlassDefinition.createFrom;
const $$createType5 = GlassArtifact.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = InviteUserInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = Organisation.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = GitRepoInfo.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = PkgRegistries.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = NeuronItem.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = EnvDeployments.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = SharePerson.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ShareAccount.createFrom;
const $$createType23 = $Create.Array($$createType22);
