// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PackageService orchestrates the Manage Packages flow: scan → GeneratePackageScripts → run scripts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as alisclient$0 from "./internal/alisclient/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CLIDefineWithInstall starts `alis define <pkg> --install` and returns the
 * operation name immediately.
 * 
 * This runs --async deliberately. A define takes minutes, and a blocking
 * invocation would hold the Wails call open for its whole duration with no
 * progress and no way to cancel. Callers poll with
 * DefineService.PollDefineOperation, exactly as the plain define flow does.
 * The chained --install still runs CLI-side once the define succeeds.
 */
export function CLIDefineWithInstall(org: string, product: string, neuron: string, version: string, commit: string, installLanguage: string): $CancellablePromise<$models.CLIPackageResult | null> {
    return $Call.ByID(1483476993, org, product, neuron, version, commit, installLanguage).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CLIPackagesInstall runs `alis packages install <pkg> --json`.
 * language, when set, limits the run to one of go/node/python/dart.
 */
export function CLIPackagesInstall(org: string, product: string, neuron: string, version: string, language: string): $CancellablePromise<$models.CLIPackageResult | null> {
    return $Call.ByID(1240612287, org, product, neuron, version, language).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CLIPackagesUpgrade runs `alis packages upgrade <pkg> --json`.
 * 
 * all also upgrades third-party packages. paths selects specific package
 * folders or manifests relative to the service — required for nested modules,
 * where the package id still names the owning service, not the dependency.
 */
export function CLIPackagesUpgrade(org: string, product: string, neuron: string, version: string, all: boolean, language: string, paths: string[]): $CancellablePromise<$models.CLIPackageResult | null> {
    return $Call.ByID(465072776, org, product, neuron, version, all, language, paths).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CancelPackageRun cancels a running script.
 */
export function CancelPackageRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(1669519566, runID);
}

/**
 * CheckVenvExists returns true if a .venv directory exists at the product build root.
 */
export function CheckVenvExists(org: string, product: string): $CancellablePromise<boolean> {
    return $Call.ByID(182031158, org, product);
}

/**
 * PollPackageRun returns new output since offset. Reuses LocalBuildChunk from buildservice.
 */
export function PollPackageRun(runID: string, offset: number): $CancellablePromise<$models.LocalBuildChunk | null> {
    return $Call.ByID(1401151733, runID, offset).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PreparePackageScripts scans the neuron build directory for language manifests, then calls
 * VscodeService/GeneratePackageScripts to obtain the shell commands for each folder.
 */
export function PreparePackageScripts(org: string, product: string, neuron: string, version: string, ignoreHidden: boolean, extraPatterns: string[]): $CancellablePromise<alisclient$0.PackageScript[]> {
    return $Call.ByID(972249452, org, product, neuron, version, ignoreHidden, extraPatterns).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ResizePackageTerminal updates the PTY window size, keeping line-wrapping correct.
 */
export function ResizePackageTerminal(runID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2164536571, runID, cols, rows);
}

/**
 * StartPackageScript launches a command in a PTY so the terminal is fully interactive.
 */
export function StartPackageScript(runID: string, command: string, workDir: string): $CancellablePromise<void> {
    return $Call.ByID(2253516098, runID, command, workDir);
}

/**
 * StartVenvSetup launches the Python venv creation command as a PTY process.
 * Mirrors the extension's Imt() — fires without blocking.
 */
export function StartVenvSetup(runID: string, org: string, product: string): $CancellablePromise<void> {
    return $Call.ByID(1646026243, runID, org, product);
}

/**
 * WritePackageInput sends keystrokes to the PTY stdin of a running process.
 */
export function WritePackageInput(runID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2728173072, runID, data);
}

// Private type creation functions
const $$createType0 = $models.CLIPackageResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.LocalBuildChunk.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = alisclient$0.PackageScript.createFrom;
const $$createType5 = $Create.Array($$createType4);
