// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PackageService orchestrates the Manage Packages flow: scan → GeneratePackageScripts → run scripts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelPackageRun cancels a running script.
 * @param {string} runID
 * @returns {$CancellablePromise<void>}
 */
export function CancelPackageRun(runID) {
    return $Call.ByID(1669519566, runID);
}

/**
 * CheckVenvExists returns true if a .venv directory exists at the product build root.
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckVenvExists(org, product) {
    return $Call.ByID(182031158, org, product);
}

/**
 * PollPackageRun returns new output since offset. Reuses the LocalBuildChunk type from buildservice.
 * @param {string} runID
 * @param {number} offset
 * @returns {$CancellablePromise<$models.LocalBuildChunk | null>}
 */
export function PollPackageRun(runID, offset) {
    return $Call.ByID(1401151733, runID, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PreparePackageScripts scans the neuron build directory for language manifests, then calls
 * VscodeService/GeneratePackageScripts to obtain the shell commands for each folder.
 * @param {string} org
 * @param {string} product
 * @param {string} neuron
 * @param {string} version
 * @returns {$CancellablePromise<$models.PackageScript[]>}
 */
export function PreparePackageScripts(org, product, neuron, version) {
    return $Call.ByID(972249452, org, product, neuron, version).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * StartPackageScript launches a script in a goroutine and stores its state under runID.
 * The shell command is run via bash -c so it inherits PATH and env.
 * @param {string} runID
 * @param {string} command
 * @param {string} workDir
 * @returns {$CancellablePromise<void>}
 */
export function StartPackageScript(runID, command, workDir) {
    return $Call.ByID(2253516098, runID, command, workDir);
}

/**
 * StartVenvSetup launches the Python venv creation command as a tracked process.
 * Mirrors the extension's Imt() — fires and does not block waiting for completion.
 * Command: python3 -m venv .venv && .venv/bin/python3 -m pip install keyring keyrings.google-artifactregistry-auth wheel && gcloud auth application-default login
 * @param {string} runID
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<void>}
 */
export function StartVenvSetup(runID, org, product) {
    return $Call.ByID(1646026243, runID, org, product);
}

// Private type creation functions
const $$createType0 = $models.LocalBuildChunk.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.PackageScript.createFrom;
const $$createType3 = $Create.Array($$createType2);
