// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PackageService orchestrates the Manage Packages flow: scan → GeneratePackageScripts → run scripts.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelPackageRun cancels a running script.
 */
export function CancelPackageRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(1669519566, runID);
}

/**
 * CheckVenvExists returns true if a .venv directory exists at the product build root.
 */
export function CheckVenvExists(org: string, product: string): $CancellablePromise<boolean> {
    return $Call.ByID(182031158, org, product);
}

/**
 * PollPackageRun returns new output since offset. Reuses LocalBuildChunk from buildservice.
 */
export function PollPackageRun(runID: string, offset: number): $CancellablePromise<$models.LocalBuildChunk | null> {
    return $Call.ByID(1401151733, runID, offset).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PreparePackageScripts scans the neuron build directory for language manifests, then calls
 * VscodeService/GeneratePackageScripts to obtain the shell commands for each folder.
 */
export function PreparePackageScripts(org: string, product: string, neuron: string, version: string): $CancellablePromise<$models.PackageScript[]> {
    return $Call.ByID(972249452, org, product, neuron, version).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ResizePackageTerminal updates the PTY window size, keeping line-wrapping correct.
 */
export function ResizePackageTerminal(runID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2164536571, runID, cols, rows);
}

/**
 * StartPackageScript launches a command in a PTY so the terminal is fully interactive.
 */
export function StartPackageScript(runID: string, command: string, workDir: string): $CancellablePromise<void> {
    return $Call.ByID(2253516098, runID, command, workDir);
}

/**
 * StartVenvSetup launches the Python venv creation command as a PTY process.
 * Mirrors the extension's Imt() — fires without blocking.
 */
export function StartVenvSetup(runID: string, org: string, product: string): $CancellablePromise<void> {
    return $Call.ByID(1646026243, runID, org, product);
}

/**
 * WritePackageInput sends keystrokes to the PTY stdin of a running process.
 */
export function WritePackageInput(runID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2728173072, runID, data);
}

// Private type creation functions
const $$createType0 = $models.LocalBuildChunk.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.PackageScript.createFrom;
const $$createType3 = $Create.Array($$createType2);
