// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.BootstrapBlockParams} params
 * @returns {$CancellablePromise<string>}
 */
export function BootstrapBlock(params) {
    return $Call.ByID(3259830753, params);
}

/**
 * CheckAuth returns true when a valid, refreshable auth token can be obtained.
 * Unlike IsLoggedIn, this actually tries to fetch/refresh the token, so it
 * returns false when the refresh token has expired even if the credentials
 * file still exists.
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckAuth() {
    return $Call.ByID(2302560144);
}

/**
 * CheckProductCloneStatus returns true if both the define and build repos for
 * the given product are already present on the local filesystem.
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckProductCloneStatus(org, product) {
    return $Call.ByID(2135548336, org, product);
}

/**
 * ContributeBlock publishes a new block version with code files via BlockVersionsService/CreateBlockVersion (LRO).
 * Returns the created version resource name, e.g. "blocks/myblock/versions/v1.0.0-experimental1".
 * @param {$models.ContributeBlockParams} params
 * @returns {$CancellablePromise<string>}
 */
export function ContributeBlock(params) {
    return $Call.ByID(2599750638, params);
}

/**
 * ContributeBlockFromCommits publishes a new block version using define and build commit SHAs.
 * This is the production path that matches the VSCode extension's worktree-based flow.
 * @param {string} instanceName
 * @param {string} defineCommitSha
 * @param {string} buildCommitSha
 * @param {number} releaseLevel
 * @param {string} releaseNotes
 * @returns {$CancellablePromise<string>}
 */
export function ContributeBlockFromCommits(instanceName, defineCommitSha, buildCommitSha, releaseLevel, releaseNotes) {
    return $Call.ByID(1195485020, instanceName, defineCommitSha, buildCommitSha, releaseLevel, releaseNotes);
}

/**
 * CreateCodeblock creates a new code block and returns its resource name (e.g. "blocks/myblock").
 * @param {$models.CreateCodeblockParams} params
 * @returns {$CancellablePromise<string>}
 */
export function CreateCodeblock(params) {
    return $Call.ByID(3659538524, params);
}

/**
 * CreateEnvironment creates a new environment under the given org/product.
 * envType: 1=DEV, 2=STAGING, 3=PROD. region must be a valid GCP region.
 * @param {string} org
 * @param {string} product
 * @param {string} displayName
 * @param {string} region
 * @param {number} envType
 * @returns {$CancellablePromise<$models.EnvInfo | null>}
 */
export function CreateEnvironment(org, product, displayName, region, envType) {
    return $Call.ByID(2295881451, org, product, displayName, region, envType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetServicesOverview fetches neurons and per-environment deployments in parallel.
 * CreateNeuron creates a new neuron (service) under the given org/product.
 * neuronId must follow the pattern: lowercase letters/digits/hyphens, ending with -v{N}.
 * @param {string} org
 * @param {string} product
 * @param {string} neuronId
 * @returns {$CancellablePromise<$models.NeuronItem | null>}
 */
export function CreateNeuron(org, product, neuronId) {
    return $Call.ByID(2867503901, org, product, neuronId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DeleteCodeblock permanently deletes a block by its ID.
 * @param {string} blockId
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCodeblock(blockId) {
    return $Call.ByID(2167564701, blockId);
}

/**
 * DeleteEnvironment deletes the environment with the given full resource name.
 * @param {string} envName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEnvironment(envName) {
    return $Call.ByID(2246279434, envName);
}

/**
 * DoInstallBlock creates an entitlement, creates the instance, then runs the installation pipeline.
 * It polls until the deployment operation completes (up to 5 minutes) before returning.
 * @param {$models.InstallBlockParams} params
 * @returns {$CancellablePromise<$models.InstallBlockResult | null>}
 */
export function DoInstallBlock(params) {
    return $Call.ByID(4070719875, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetBlockAccessData fetches the IAM policy for a block and enriches each member with user details.
 * @param {string} blockId
 * @returns {$CancellablePromise<$models.BlockAccessData | null>}
 */
export function GetBlockAccessData(blockId) {
    return $Call.ByID(171805929, blockId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetBlockCommits returns recent commits from the build or define repo for a given instance.
 * repoType must be "build" or "define".
 * @param {string} instanceName
 * @param {string} repoType
 * @param {number} limit
 * @returns {$CancellablePromise<$models.BlockCommit[]>}
 */
export function GetBlockCommits(instanceName, repoType, limit) {
    return $Call.ByID(2047809995, instanceName, repoType, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetCodeblock fetches a single block by its short ID (e.g. "skills").
 * @param {string} blockId
 * @returns {$CancellablePromise<$models.Codeblock | null>}
 */
export function GetCodeblock(blockId) {
    return $Call.ByID(3775238228, blockId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetCodeblockDoc returns documentation markdown for a specific block version.
 * audience is "user" or "agent".
 * @param {string} versionName
 * @param {string} audience
 * @returns {$CancellablePromise<string>}
 */
export function GetCodeblockDoc(versionName, audience) {
    return $Call.ByID(2050061994, versionName, audience);
}

/**
 * GetCodeblockMembers fetches the IAM members for a block and resolves their avatar URLs.
 * It chains GetIamPolicy → BatchRetrieveMaskedUsers.
 * @param {string} blockId
 * @returns {$CancellablePromise<$models.CodeblockMember[]>}
 */
export function GetCodeblockMembers(blockId) {
    return $Call.ByID(854804143, blockId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetCodeblockVersion returns full details for a block version including files.
 * versionName is the resource name, e.g. "blocks/bb6b/versions/1.0.0-experimental1".
 * @param {string} versionName
 * @returns {$CancellablePromise<$models.CodeblockVersion | null>}
 */
export function GetCodeblockVersion(versionName) {
    return $Call.ByID(2809120232, versionName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetEnvironmentVariables fetches the variables for a single environment.
 * envName is the full resource name, e.g. "organisations/voyage/products/vp/environments/1y2ozw66zv6p3".
 * @param {string} envName
 * @returns {$CancellablePromise<$models.EnvVariable[]>}
 */
export function GetEnvironmentVariables(envName) {
    return $Call.ByID(3106139540, envName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * GetMyPrimaryAccountID returns the caller's primary account resource name (e.g. "accounts/8na6ap").
 * @returns {$CancellablePromise<string>}
 */
export function GetMyPrimaryAccountID() {
    return $Call.ByID(1119095964);
}

/**
 * GetOrganisationProject returns the GCP project associated with an organisation.
 * @param {string} org
 * @returns {$CancellablePromise<$models.GCPProject | null>}
 */
export function GetOrganisationProject(org) {
    return $Call.ByID(1082294977, org).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.ProductOverview | null>}
 */
export function GetProductOverview(org, product) {
    return $Call.ByID(4137998258, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.ServicesOverview | null>}
 */
export function GetServicesOverview(org, product) {
    return $Call.ByID(1035339913, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * GetShareData fetches the IAM policy for the product and enriches each member
 * with display names via BatchRetrieveMaskedUsers and RetrieveMaskedAccounts.
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.ShareData | null>}
 */
export function GetShareData(org, product) {
    return $Call.ByID(1908839309, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * GetUserProfile fetches name and photo for the logged-in user via
 * BatchRetrieveMaskedUsers, using the sub from the stored token as the user ID.
 * @returns {$CancellablePromise<$models.UserProfile | null>}
 */
export function GetUserProfile() {
    return $Call.ByID(1754949162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * GetWorkstationURI returns the web IDE URI for the current user's workstation.
 * Returns "" (no error) if the workstation is still being provisioned or is unavailable.
 * @returns {$CancellablePromise<string>}
 */
export function GetWorkstationURI() {
    return $Call.ByID(1516947257);
}

/**
 * IsLoggedIn returns true when console credentials exist.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLoggedIn() {
    return $Call.ByID(1203503551);
}

/**
 * ListAccountUsers returns all users in the caller's primary account, used to
 * populate IAM member pickers.
 * @returns {$CancellablePromise<$models.AccountUser[]>}
 */
export function ListAccountUsers() {
    return $Call.ByID(2615726607).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * ListBlockPlans returns the available entitlement plans for a block.
 * @param {string} blockId
 * @returns {$CancellablePromise<$models.BlockPlan[]>}
 */
export function ListBlockPlans(blockId) {
    return $Call.ByID(2087595101, blockId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * ListBlockRoles returns the IAM roles available for a block via RolesService/ListRoles.
 * Role proto: field 1 = name, field 5 = title.
 * @param {string} blockId
 * @returns {$CancellablePromise<$models.BlockRole[]>}
 */
export function ListBlockRoles(blockId) {
    return $Call.ByID(392865116, blockId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * ListCodeblockInstances lists installed instances for a block.
 * @param {string} blockId
 * @returns {$CancellablePromise<$models.CodeblockInstance[]>}
 */
export function ListCodeblockInstances(blockId) {
    return $Call.ByID(2469208404, blockId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * ListCodeblockVersions lists available versions for a block.
 * @param {string} blockId
 * @returns {$CancellablePromise<$models.CodeblockVersion[]>}
 */
export function ListCodeblockVersions(blockId) {
    return $Call.ByID(1837251873, blockId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * ListCodeblocks fetches all available codeblocks from alis.bl.blocks.v1.BlocksService.
 * @returns {$CancellablePromise<$models.Codeblock[]>}
 */
export function ListCodeblocks() {
    return $Call.ByID(2482784325).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.EnvInfo[]>}
 */
export function ListEnvironments(org, product) {
    return $Call.ByID(535981680, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * ListInstallNeurons returns the neurons (packages) in the given org/product for install location picker.
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.InstallNeuron[]>}
 */
export function ListInstallNeurons(org, product) {
    return $Call.ByID(426248599, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * ListInstallOrgs returns all organisations the user belongs to (for install location picker).
 * @returns {$CancellablePromise<$models.Organisation[]>}
 */
export function ListInstallOrgs() {
    return $Call.ByID(3252611686).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.InviteInfo[]>}
 */
export function ListInvites(org, product) {
    return $Call.ByID(1503809804, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.LandingZonesData | null>}
 */
export function ListLandingZones() {
    return $Call.ByID(3242955384).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * ListMyCodeblocks returns only the blocks published by the current user's account.
 * @returns {$CancellablePromise<$models.Codeblock[]>}
 */
export function ListMyCodeblocks() {
    return $Call.ByID(657485483).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * @param {string} org
 * @returns {$CancellablePromise<$models.ProductSummary[]>}
 */
export function ListProducts(org) {
    return $Call.ByID(1517062122, org).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * Login triggers the PKCE OAuth2 flow. The browser opens, the user authenticates,
 * and tokens are saved to ~/.alis/console-credentials.json.
 * @returns {$CancellablePromise<void>}
 */
export function Login() {
    return $Call.ByID(1314230687);
}

/**
 * Logout removes the stored console credentials, signing the user out.
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(3281387172);
}

/**
 * OpenBlockWorktrees creates git worktrees for an instance's build and define repos.
 * It returns the root worktree path, e.g. "{tmpdir}/.alis-blocks-worktrees/{blockId}/{packageId}/{instanceId}/".
 * @param {string} instanceName
 * @returns {$CancellablePromise<string>}
 */
export function OpenBlockWorktrees(instanceName) {
    return $Call.ByID(2551618999, instanceName);
}

/**
 * OpenForgejoWindow opens a new WebView window pointed at the given Forgejo URL.
 * It routes the request through a local proxy that injects auth headers.
 * @param {string} repoURL
 * @returns {$CancellablePromise<void>}
 */
export function OpenForgejoWindow(repoURL) {
    return $Call.ByID(3555025818, repoURL);
}

/**
 * OpenInIDE opens the product in the specified IDE.
 * ide must be "web", "vscode", or "cursor".
 * productName is the full resource name, e.g. "organisations/voyage/products/vp".
 * @param {string} productName
 * @param {string} ide
 * @returns {$CancellablePromise<void>}
 */
export function OpenInIDE(productName, ide) {
    return $Call.ByID(3656788695, productName, ide);
}

/**
 * OpenWorktreeInFinder opens the given directory in macOS Finder.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function OpenWorktreeInFinder(path) {
    return $Call.ByID(1416065536, path);
}

/**
 * ScanNeuronFiles scans the local neuron version directory and returns build/infra files.
 * Returns a soft error (NeuronScanResult.Error) when the path is missing or unreadable; no Go error.
 * @param {string} neuronPackage
 * @returns {$CancellablePromise<$models.NeuronScanResult | null>}
 */
export function ScanNeuronFiles(neuronPackage) {
    return $Call.ByID(1856011391, neuronPackage).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType50($result);
    }));
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1786829241, app);
}

/**
 * SetEnvironmentVariables replaces all variables on an environment by calling
 * UpdateEnvironment with an update_mask of "envs". Variables are field 8
 * (repeated Environment.Env sub-messages: field 1=name/label, field 2=value).
 * @param {string} envName
 * @param {$models.EnvVariable[]} vars
 * @returns {$CancellablePromise<void>}
 */
export function SetEnvironmentVariables(envName, vars) {
    return $Call.ByID(1096665320, envName, vars);
}

/**
 * SwitchEnvironment updates the local .alis/.env file to reflect the newly
 * selected environment. It rewrites the env-specific system variables
 * (ALIS_OS_PROJECT, ALIS_PROJECT_NR, ALIS_REGION, ALIS_MANAGED_SPANNER_DB,
 * ALIS_OS_ORG_BACKEND_PRODUCT_PREFIX) and regenerates the Builder Managed
 * section with the environment's variables from the API.
 * If no local .env file exists the call is a no-op.
 * @param {string} org
 * @param {string} product
 * @param {string} envName
 * @param {string} projectID
 * @param {string} projectNumber
 * @param {string} region
 * @returns {$CancellablePromise<void>}
 */
export function SwitchEnvironment(org, product, envName, projectID, projectNumber, region) {
    return $Call.ByID(3506000719, org, product, envName, projectID, projectNumber, region);
}

/**
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.SyncReposResult | null>}
 */
export function SyncRepos(org, product) {
    return $Call.ByID(1467472974, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType52($result);
    }));
}

/**
 * UninstallCodeblockInstance uninstalls an instance by resource name (e.g. "blocks/bb6b/instances/631").
 * The configuration is preserved on the server for potential reinstallation.
 * Returns after the resulting LRO completes (up to 5 minutes).
 * @param {string} instanceName
 * @returns {$CancellablePromise<void>}
 */
export function UninstallCodeblockInstance(instanceName) {
    return $Call.ByID(598414329, instanceName);
}

/**
 * UpdateBlockAccess adds or removes a single member from a role on a block's IAM policy.
 * member must be in "user:ID" IAM form. grant=true to add, grant=false to remove.
 * @param {string} blockId
 * @param {string} role
 * @param {string} member
 * @param {boolean} grant
 * @returns {$CancellablePromise<void>}
 */
export function UpdateBlockAccess(blockId, role, member, grant) {
    return $Call.ByID(3240839382, blockId, role, member, grant);
}

/**
 * parseCreateBlockName extracts the resource name (field 1) from the returned Block.
 * UpdateCodeblock calls BlocksService/UpdateBlock with the given params.
 * @param {$models.CreateCodeblockParams} params
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCodeblock(params) {
    return $Call.ByID(2070720319, params);
}

/**
 * UpdateEnvironment updates the displayName of an existing environment.
 * envName is the full resource name.
 * @param {string} envName
 * @param {string} displayName
 * @returns {$CancellablePromise<$models.EnvInfo | null>}
 */
export function UpdateEnvironment(envName, displayName) {
    return $Call.ByID(828266076, envName, displayName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * UpgradeCodeblockInstance upgrades an instance to a different block version.
 * instanceName is the full resource name (e.g. "blocks/bb6b/instances/631").
 * blockVersionName is the full version resource name (e.g. "blocks/bb6b/versions/1.0.0-experimental1").
 * Returns after the resulting LRO completes (up to 5 minutes).
 * @param {string} instanceName
 * @param {string} blockVersionName
 * @returns {$CancellablePromise<void>}
 */
export function UpgradeCodeblockInstance(instanceName, blockVersionName) {
    return $Call.ByID(1284035243, instanceName, blockVersionName);
}

// Private type creation functions
const $$createType0 = $models.EnvInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.NeuronItem.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.InstallBlockResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.BlockAccessData.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.BlockCommit.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.Codeblock.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.CodeblockMember.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.CodeblockVersion.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.EnvVariable.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.GCPProject.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $models.ProductOverview.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $models.ServicesOverview.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $models.ShareData.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $models.UserProfile.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = $models.AccountUser.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = $models.BlockPlan.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = $models.BlockRole.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = $models.CodeblockInstance.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = $Create.Array($$createType14);
const $$createType37 = $Create.Array($$createType10);
const $$createType38 = $Create.Array($$createType0);
const $$createType39 = $models.InstallNeuron.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = $models.Organisation.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = $models.InviteInfo.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = $models.LandingZonesData.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = $models.ProductSummary.createFrom;
const $$createType48 = $Create.Array($$createType47);
const $$createType49 = $models.NeuronScanResult.createFrom;
const $$createType50 = $Create.Nullable($$createType49);
const $$createType51 = $models.SyncReposResult.createFrom;
const $$createType52 = $Create.Nullable($$createType51);
