// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateEnvironment creates a new environment under the given org/product.
 * envType: 1=DEV, 2=STAGING, 3=PROD. region must be a valid GCP region.
 * @param {string} org
 * @param {string} product
 * @param {string} displayName
 * @param {string} region
 * @param {number} envType
 * @returns {$CancellablePromise<$models.EnvInfo | null>}
 */
export function CreateEnvironment(org, product, displayName, region, envType) {
    return $Call.ByID(2295881451, org, product, displayName, region, envType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteEnvironment deletes the environment with the given full resource name.
 * @param {string} envName
 * @returns {$CancellablePromise<void>}
 */
export function DeleteEnvironment(envName) {
    return $Call.ByID(2246279434, envName);
}

/**
 * GetEnvironmentVariables fetches the variables for a single environment.
 * envName is the full resource name, e.g. "organisations/voyage/products/vp/environments/1y2ozw66zv6p3".
 * @param {string} envName
 * @returns {$CancellablePromise<$models.EnvVariable[]>}
 */
export function GetEnvironmentVariables(envName) {
    return $Call.ByID(3106139540, envName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.ProductOverview | null>}
 */
export function GetProductOverview(org, product) {
    return $Call.ByID(4137998258, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetServicesOverview fetches neurons and per-environment deployments in parallel.
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.ServicesOverview | null>}
 */
export function GetServicesOverview(org, product) {
    return $Call.ByID(1035339913, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetShareData fetches the IAM policy for the product and enriches each member
 * with display names via BatchRetrieveMaskedUsers and RetrieveMaskedAccounts.
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.ShareData | null>}
 */
export function GetShareData(org, product) {
    return $Call.ByID(1908839309, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetUserProfile fetches name and photo for the logged-in user via
 * BatchRetrieveMaskedUsers, using the sub from the stored token as the user ID.
 * @returns {$CancellablePromise<$models.UserProfile | null>}
 */
export function GetUserProfile() {
    return $Call.ByID(1754949162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * IsLoggedIn returns true when console credentials exist.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsLoggedIn() {
    return $Call.ByID(1203503551);
}

/**
 * ListCodeblocks fetches all available codeblocks from alis.bl.blocks.v1.BlocksService.
 * @returns {$CancellablePromise<$models.Codeblock[]>}
 */
export function ListCodeblocks() {
    return $Call.ByID(2482784325).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.EnvInfo[]>}
 */
export function ListEnvironments(org, product) {
    return $Call.ByID(535981680, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.InviteInfo[]>}
 */
export function ListInvites(org, product) {
    return $Call.ByID(1503809804, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.LandingZonesData | null>}
 */
export function ListLandingZones() {
    return $Call.ByID(3242955384).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @param {string} org
 * @returns {$CancellablePromise<$models.ProductSummary[]>}
 */
export function ListProducts(org) {
    return $Call.ByID(1517062122, org).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * Login triggers the PKCE OAuth2 flow. The browser opens, the user authenticates,
 * and tokens are saved to ~/.alis/console-credentials.json.
 * @returns {$CancellablePromise<void>}
 */
export function Login() {
    return $Call.ByID(1314230687);
}

/**
 * Logout removes the stored console credentials, signing the user out.
 * @returns {$CancellablePromise<void>}
 */
export function Logout() {
    return $Call.ByID(3281387172);
}

/**
 * SetEnvironmentVariables replaces all variables on an environment by calling
 * UpdateEnvironment with an update_mask of "envs". Variables are field 8
 * (repeated Environment.Env sub-messages: field 1=name/label, field 2=value).
 * @param {string} envName
 * @param {$models.EnvVariable[]} vars
 * @returns {$CancellablePromise<void>}
 */
export function SetEnvironmentVariables(envName, vars) {
    return $Call.ByID(1096665320, envName, vars);
}

/**
 * @param {string} org
 * @param {string} product
 * @returns {$CancellablePromise<$models.SyncReposResult | null>}
 */
export function SyncRepos(org, product) {
    return $Call.ByID(1467472974, org, product).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * UpdateEnvironment updates the displayName of an existing environment.
 * envName is the full resource name.
 * @param {string} envName
 * @param {string} displayName
 * @returns {$CancellablePromise<$models.EnvInfo | null>}
 */
export function UpdateEnvironment(envName, displayName) {
    return $Call.ByID(828266076, envName, displayName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.EnvInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.EnvVariable.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ProductOverview.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.ServicesOverview.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.ShareData.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.UserProfile.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.Codeblock.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $Create.Array($$createType0);
const $$createType15 = $models.InviteInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.LandingZonesData.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $models.ProductSummary.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.SyncReposResult.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
