// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetProductOverview(org: string, product: string): $CancellablePromise<$models.ProductOverview | null> {
    return $Call.ByID(4137998258, org, product).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetServicesOverview fetches neurons and per-environment deployments in parallel.
 */
export function GetServicesOverview(org: string, product: string): $CancellablePromise<$models.ServicesOverview | null> {
    return $Call.ByID(1035339913, org, product).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * IsLoggedIn returns true when console credentials exist.
 */
export function IsLoggedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(1203503551);
}

export function ListEnvironments(org: string, product: string): $CancellablePromise<$models.EnvInfo[]> {
    return $Call.ByID(535981680, org, product).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListInvites returns the invites for a product's build landing zone.
 * The parent resource is organisations/{org}/products/{product}.
 */
export function ListInvites(org: string, product: string): $CancellablePromise<$models.InviteInfo[]> {
    return $Call.ByID(1503809804, org, product).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Login triggers the PKCE OAuth2 flow. The browser opens, the user authenticates,
 * and tokens are saved to ~/.alis/console-credentials.json.
 */
export function Login(): $CancellablePromise<void> {
    return $Call.ByID(1314230687);
}

// Private type creation functions
const $$createType0 = $models.ProductOverview.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ServicesOverview.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.EnvInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.InviteInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
