// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetProductOverview(org: string, product: string): $CancellablePromise<$models.ProductOverview | null> {
    return $Call.ByID(4137998258, org, product).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetServicesOverview fetches neurons and per-environment deployments in parallel.
 */
export function GetServicesOverview(org: string, product: string): $CancellablePromise<$models.ServicesOverview | null> {
    return $Call.ByID(1035339913, org, product).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetShareData fetches the IAM policy for the product and enriches each member
 * with display names via BatchRetrieveMaskedUsers and RetrieveMaskedAccounts.
 */
export function GetShareData(org: string, product: string): $CancellablePromise<$models.ShareData | null> {
    return $Call.ByID(1908839309, org, product).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * IsLoggedIn returns true when console credentials exist.
 */
export function IsLoggedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(1203503551);
}

export function ListEnvironments(org: string, product: string): $CancellablePromise<$models.EnvInfo[]> {
    return $Call.ByID(535981680, org, product).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListInvites(org: string, product: string): $CancellablePromise<$models.InviteInfo[]> {
    return $Call.ByID(1503809804, org, product).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListLandingZones(): $CancellablePromise<$models.LandingZonesData | null> {
    return $Call.ByID(3242955384).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListProducts(org: string): $CancellablePromise<$models.ProductSummary[]> {
    return $Call.ByID(1517062122, org).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * Login triggers the PKCE OAuth2 flow. The browser opens, the user authenticates,
 * and tokens are saved to ~/.alis/console-credentials.json.
 */
export function Login(): $CancellablePromise<void> {
    return $Call.ByID(1314230687);
}

// Private type creation functions
const $$createType0 = $models.ProductOverview.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ServicesOverview.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ShareData.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.EnvInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.InviteInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.LandingZonesData.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.ProductSummary.createFrom;
const $$createType13 = $Create.Array($$createType12);
