// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProtoDecodeService compiles an org's cloned "define" repo (~/alis.build/{org}/define)
 * into linked proto descriptors in-process — no protoc/buf binary required — so Spanner
 * BYTES columns can be decoded into JSON using the org's real message definitions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DecodeProtoBytes decodes a base64-encoded Spanner BYTES value as the given proto
 * message type (found in the org's cloned define repo) and returns pretty JSON.
 * Decoding an unrelated message type will not necessarily error — proto3's wire format
 * is permissive — so the result should be treated as best-effort, not a correctness
 * guarantee that the chosen type is right.
 */
export function DecodeProtoBytes(org: string, base64Data: string, messageFullName: string): $CancellablePromise<string> {
    return $Call.ByID(1986527782, org, base64Data, messageFullName);
}

/**
 * GetSpannerColumnProtoTypes returns the column -> proto message type mapping declared
 * in spanner.tf (infra/spanner.tf under the product's build repo) for the given table.
 * Spanner's own PROTO<> column metadata only covers columns using that native type;
 * spanner.tf is the authoritative source and also covers columns Spanner exposes as
 * plain BYTES. Returns an empty map (not an error) if the table has no declared mapping.
 */
export function GetSpannerColumnProtoTypes(org: string, product: string, table: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2320030373, org, product, table).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListProtoMessageTypes returns every message type discovered in the org's cloned
 * define repo, for a UI type picker.
 */
export function ListProtoMessageTypes(org: string): $CancellablePromise<$models.ProtoMessageInfo[]> {
    return $Call.ByID(3806347165, org).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RefreshProtoIndex invalidates the cached descriptors for an org and recompiles them,
 * e.g. after SyncRepos pulls new proto changes into the define repo.
 */
export function RefreshProtoIndex(org: string): $CancellablePromise<void> {
    return $Call.ByID(3122102086, org);
}

/**
 * RefreshSpannerSchemaIndex invalidates the cached spanner.tf scan for an org+product
 * and rescans, e.g. after SyncRepos pulls in infra changes.
 */
export function RefreshSpannerSchemaIndex(org: string, product: string): $CancellablePromise<void> {
    return $Call.ByID(38302574, org, product);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.ProtoMessageInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
