// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearRuns removes all past runs for a workflow, skipping any that are still
 * active. Returns the number of runs deleted.
 */
export function ClearRuns(workflowID: string): $CancellablePromise<number> {
    return $Call.ByID(2013056683, workflowID);
}

/**
 * CloneWorkflow creates an editable copy of any workflow (including templates).
 */
export function CloneWorkflow(id: string): $CancellablePromise<$models.Workflow | null> {
    return $Call.ByID(2060329672, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateWorkflow(params: $models.UpsertWorkflowParams): $CancellablePromise<$models.Workflow | null> {
    return $Call.ByID(3307618937, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteRun removes a single past run and its step runs. Active (still-running)
 * runs cannot be deleted.
 */
export function DeleteRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(2627270676, runID);
}

export function DeleteWorkflow(id: string): $CancellablePromise<void> {
    return $Call.ByID(3132870458, id);
}

/**
 * ExportWorkflow writes workflow id to path as JSON, matching the shape
 * ImportWorkflow-style frontend logic expects (name/description/args/steps).
 * Writing via a Go-side file write (rather than a browser blob download,
 * which WKWebView/WebView2 don't reliably support) is what lets this work
 * inside the Wails webview.
 */
export function ExportWorkflow(id: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2565138159, id, path);
}

export function GetRun(runID: string): $CancellablePromise<$models.WorkflowRun | null> {
    return $Call.ByID(694511473, runID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetWorkflow(id: string): $CancellablePromise<$models.Workflow | null> {
    return $Call.ByID(2751531297, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListRuns(workflowID: string, limit: number): $CancellablePromise<$models.WorkflowRun[]> {
    return $Call.ByID(1918677794, workflowID, limit).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListWorkflows(): $CancellablePromise<$models.Workflow[]> {
    return $Call.ByID(4184559162).then(($result: any) => {
        return $$createType5($result);
    });
}

export function PollRunLogs(runID: string, offset: number): $CancellablePromise<$models.RunLogChunk | null> {
    return $Call.ByID(3468137961, runID, offset).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * RunWorkflow starts a run of workflow id. startPosition lets the run begin
 * partway through: steps whose Position is below it are recorded as
 * 'skipped' up front and never executed, so a failed/edited step can be
 * re-run without repeating earlier side-effecting steps. Pass 0 to run the
 * whole workflow from the beginning.
 */
export function RunWorkflow(id: string, argValues: { [_ in string]?: string }, startPosition: number): $CancellablePromise<string> {
    return $Call.ByID(45429760, id, argValues, startPosition);
}

/**
 * SendRunInput writes user-typed input to the currently running step's shell,
 * e.g. to answer an interactive prompt (like corepack's download confirmation).
 */
export function SendRunInput(runID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3127346285, runID, data);
}

export function StopRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(4293969093, runID);
}

export function UpdateWorkflow(id: string, params: $models.UpsertWorkflowParams): $CancellablePromise<void> {
    return $Call.ByID(1443061788, id, params);
}

// Private type creation functions
const $$createType0 = $models.Workflow.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.WorkflowRun.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType2);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $models.RunLogChunk.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
